/**
 * Config plugin: scope Android's cleartext (HTTP) traffic allowance to
 * genuinely local/private hosts, matching the iOS `NSAllowsLocalNetworking`
 * posture in app.json's `ios.infoPlist.NSAppTransportSecurity`.
 *
 * `app.json`'s `android.usesCleartextTraffic` (and expo-build-properties'
 * equivalent option) is a single blanket boolean — there is no way to scope
 * it to specific hosts from app.json alone. Android *does* support per-host
 * scoping, but only via a `network_security_config.xml` resource wired up
 * through the manifest's `android:networkSecurityConfig` attribute, which
 * isn't exposed by any Expo config field — hence this small custom plugin.
 *
 * Known Android platform limitation: `<domain>` entries in a network security
 * config must be literal hostnames/IPs (with `includeSubdomains` for suffix
 * wildcarding) — there is no CIDR/range syntax. So unlike iOS, which
 * classifies RFC1918 addresses dynamically at the OS level, this config
 * cannot grant cleartext to an arbitrary LAN IP (e.g. a school's on-prem
 * server at 192.168.1.50) by range. It covers the two cases this app
 * actually documents as legitimate: the Android emulator's host-loopback
 * alias (10.0.2.2) and `.local` mDNS hostnames for on-prem discovery. A
 * deployment that must reach a bare private IP over HTTP should either use
 * an mDNS hostname instead, terminate HTTPS at the on-prem server (even with
 * an internal CA), or extend the domain list below for that specific build.
 */
const { withAndroidManifest, withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const RESOURCE_NAME = "network_security_config";

const NETWORK_SECURITY_CONFIG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withAndroidNetworkSecurityConfig.js — do not edit the
  built android/ project directly, edit that plugin instead (this file is
  regenerated on every "expo prebuild").

  Cleartext (HTTP) is permitted only to loopback, the Android emulator's
  host alias, and .local mDNS hosts — see setApiBase() in
  mobile/src/api/client.ts for the matching client-side URL validation.
  Every other host must use HTTPS.
-->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">localhost</domain>
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">10.0.2.2</domain>
        <domain includeSubdomains="true">local</domain>
    </domain-config>
    <base-config cleartextTrafficPermitted="false" />
</network-security-config>
`;

function withNetworkSecurityConfigFile(config) {
  return withDangerousMod(config, [
    "android",
    async (config) => {
      const xmlDir = path.join(config.modRequest.platformProjectRoot, "app/src/main/res/xml");
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, `${RESOURCE_NAME}.xml`), NETWORK_SECURITY_CONFIG_XML);
      return config;
    },
  ]);
}

function withNetworkSecurityConfigManifest(config) {
  return withAndroidManifest(config, (config) => {
    const application = config.modResults.manifest.application?.[0];
    if (application) {
      application.$["android:networkSecurityConfig"] = `@xml/${RESOURCE_NAME}`;
      // The domain-config above is the single source of truth for which
      // hosts may use cleartext; keep the blanket flag off so nothing can
      // widen it back to "any host" without touching this file.
      application.$["android:usesCleartextTraffic"] = "false";
    }
    return config;
  });
}

module.exports = function withAndroidNetworkSecurityConfig(config) {
  config = withNetworkSecurityConfigFile(config);
  config = withNetworkSecurityConfigManifest(config);
  return config;
};
