import { ModuleConfig } from "./types";

export const studentsModule: ModuleConfig = {
  key: "students",
  title: "Students",
  icon: "🎓",
  feature: "students",
  endpoint: "/students",
  titleField: "first_name",
  subtitleField: "class_name",
  searchFields: ["first_name", "last_name", "admission_no", "roll_no"],
  listColumns: [
    { key: "admission_no", label: "Admission No" },
    { key: "class_name", label: "Class" },
    { key: "section", label: "Section" },
    { key: "student_status", label: "Status" },
  ],
  formFields: [
    { key: "admission_no", label: "Admission No", type: "text", required: true },
    { key: "first_name", label: "First Name", type: "text", required: true },
    { key: "last_name", label: "Last Name", type: "text" },
    { key: "gender", label: "Gender", type: "select", options: [
      { label: "Male", value: "Male" }, { label: "Female", value: "Female" }, { label: "Other", value: "Other" },
    ] },
    { key: "dob", label: "Date of Birth (YYYY-MM-DD)", type: "date" },
    { key: "class_name", label: "Class", type: "text" },
    { key: "section", label: "Section", type: "text" },
    { key: "house", label: "House", type: "text" },
    { key: "admission_date", label: "Admission Date (YYYY-MM-DD)", type: "date" },
    { key: "student_status", label: "Status", type: "select", options: [
      { label: "Active", value: "Active" }, { label: "Inactive", value: "Inactive" },
    ] },
    { key: "residential_type", label: "Residential Type", type: "select", options: [
      { label: "Day Scholar", value: "Day Scholar" }, { label: "Hosteller", value: "Hosteller" },
    ] },
    { key: "father_name", label: "Father's Name", type: "text" },
    { key: "mother_name", label: "Mother's Name", type: "text" },
    { key: "guardian_name", label: "Guardian Name", type: "text" },
    { key: "guardian_phone", label: "Guardian Phone", type: "phone" },
    { key: "guardian_email", label: "Guardian Email", type: "email" },
    { key: "blood_group", label: "Blood Group", type: "text" },
    { key: "medical_notes", label: "Medical Notes", type: "textarea" },
    { key: "allergies", label: "Allergies", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const teachersModule: ModuleConfig = {
  key: "teachers",
  title: "Teachers",
  icon: "🧑‍🏫",
  feature: "teachers",
  endpoint: "/teachers",
  titleField: "name",
  subtitleField: "department",
  searchFields: ["name", "employee_no", "email", "subject"],
  listColumns: [
    { key: "employee_no", label: "Employee No" },
    { key: "subject", label: "Subject" },
    { key: "assigned_class", label: "Assigned Class" },
  ],
  formFields: [
    { key: "employee_no", label: "Employee No", type: "text", required: true },
    { key: "name", label: "Full Name", type: "text", required: true },
    { key: "email", label: "Email", type: "email" },
    { key: "phone", label: "Phone", type: "phone" },
    { key: "gender", label: "Gender", type: "select", options: [
      { label: "Male", value: "Male" }, { label: "Female", value: "Female" }, { label: "Other", value: "Other" },
    ] },
    { key: "department", label: "Department", type: "text" },
    { key: "subject", label: "Subject", type: "text" },
    { key: "assigned_class", label: "Assigned Class", type: "text" },
    { key: "qualification", label: "Qualification", type: "text" },
    { key: "joining_date", label: "Joining Date (YYYY-MM-DD)", type: "date" },
    { key: "employment_type", label: "Employment Type", type: "text" },
    { key: "salary_grade", label: "Salary Grade", type: "text" },
    { key: "address", label: "Address", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const classesModule: ModuleConfig = {
  key: "classes",
  title: "Classes",
  icon: "🏫",
  feature: "classes",
  endpoint: "/classes",
  titleField: "class_name",
  subtitleField: "section",
  searchFields: ["class_name", "section", "class_teacher"],
  listColumns: [
    { key: "section", label: "Section" },
    { key: "class_teacher", label: "Class Teacher" },
    { key: "room_no", label: "Room" },
  ],
  formFields: [
    { key: "class_name", label: "Class Name", type: "text", required: true },
    { key: "section", label: "Section", type: "text", required: true },
    { key: "class_teacher", label: "Class Teacher", type: "text" },
    { key: "academic_year", label: "Academic Year", type: "text" },
    { key: "room_no", label: "Room No", type: "text" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const examsModule: ModuleConfig = {
  key: "exams",
  title: "Exams",
  icon: "📝",
  feature: "exams",
  endpoint: "/exams",
  titleField: "exam_name",
  subtitleField: "exam_type",
  searchFields: ["exam_name", "exam_type", "class_name"],
  listColumns: [
    { key: "class_name", label: "Class" },
    { key: "section", label: "Section" },
    { key: "exam_date", label: "Date" },
  ],
  formFields: [
    { key: "exam_name", label: "Exam Name", type: "text", required: true },
    { key: "exam_type", label: "Exam Type", type: "text" },
    { key: "class_name", label: "Class", type: "text" },
    { key: "section", label: "Section", type: "text" },
    { key: "exam_date", label: "Exam Date (YYYY-MM-DD)", type: "date" },
    { key: "academic_year", label: "Academic Year", type: "text" },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const feesModule: ModuleConfig = {
  key: "fees",
  title: "Fees",
  icon: "💰",
  feature: "fees",
  endpoint: "/fees",
  titleField: "fee_type",
  subtitleField: "payment_status",
  searchFields: ["fee_type", "receipt_no", "payment_status"],
  listColumns: [
    { key: "total_amount", label: "Total" },
    { key: "paid_amount", label: "Paid" },
    { key: "due_amount", label: "Due" },
    { key: "payment_status", label: "Status" },
  ],
  formFields: [
    { key: "student_id", label: "Student ID", type: "number", required: true },
    { key: "fee_type", label: "Fee Type", type: "text", required: true },
    { key: "total_amount", label: "Total Amount", type: "number", required: true },
    { key: "paid_amount", label: "Paid Amount", type: "number" },
    { key: "due_date", label: "Due Date (YYYY-MM-DD)", type: "date" },
    { key: "payment_date", label: "Payment Date (YYYY-MM-DD)", type: "date" },
    { key: "receipt_no", label: "Receipt No", type: "text" },
    { key: "academic_year", label: "Academic Year", type: "text" },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const accountingModule: ModuleConfig = {
  key: "accounting",
  title: "Accounting",
  icon: "🧾",
  feature: "accounting",
  endpoint: "/accounting/entries",
  titleField: "category",
  subtitleField: "entry_type",
  searchFields: ["category", "entry_type", "payment_mode", "reference_no"],
  listColumns: [
    { key: "entry_type", label: "Type" },
    { key: "amount", label: "Amount" },
    { key: "entry_date", label: "Date" },
  ],
  formFields: [
    { key: "entry_date", label: "Entry Date (YYYY-MM-DD)", type: "date", required: true },
    { key: "entry_type", label: "Type", type: "select", required: true, options: [
      { label: "Income", value: "Income" }, { label: "Expense", value: "Expense" },
    ] },
    { key: "category", label: "Category", type: "text", required: true },
    { key: "amount", label: "Amount", type: "number", required: true },
    { key: "payment_mode", label: "Payment Mode", type: "text" },
    { key: "reference_no", label: "Reference No", type: "text" },
    { key: "description", label: "Description", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const timetableModule: ModuleConfig = {
  key: "timetable",
  title: "Timetable",
  icon: "🕐",
  feature: "timetable",
  endpoint: "/timetable",
  titleField: "subject",
  subtitleField: "day_of_week",
  searchFields: ["subject", "day_of_week", "room", "teacher_name_snapshot"],
  listColumns: [
    { key: "day_of_week", label: "Day" },
    { key: "period_no", label: "Period" },
    { key: "start_time", label: "Start" },
  ],
  formFields: [
    { key: "day_of_week", label: "Day of Week", type: "select", required: true, options: [
      { label: "Monday", value: "Monday" }, { label: "Tuesday", value: "Tuesday" }, { label: "Wednesday", value: "Wednesday" },
      { label: "Thursday", value: "Thursday" }, { label: "Friday", value: "Friday" }, { label: "Saturday", value: "Saturday" },
    ] },
    { key: "period_no", label: "Period No", type: "number", required: true },
    { key: "subject", label: "Subject", type: "text" },
    { key: "class_name_snapshot", label: "Class", type: "text" },
    { key: "section_snapshot", label: "Section", type: "text" },
    { key: "teacher_name_snapshot", label: "Teacher", type: "text" },
    { key: "start_time", label: "Start Time (HH:MM)", type: "text" },
    { key: "end_time", label: "End Time (HH:MM)", type: "text" },
    { key: "room", label: "Room", type: "text" },
    { key: "academic_year", label: "Academic Year", type: "text" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const homeworkModule: ModuleConfig = {
  key: "homework",
  title: "Homework",
  icon: "📚",
  feature: "homework",
  endpoint: "/homework",
  titleField: "title",
  subtitleField: "class_name",
  searchFields: ["title", "class_name", "subject"],
  listColumns: [
    { key: "class_name", label: "Class" },
    { key: "subject", label: "Subject" },
    { key: "due_date", label: "Due" },
  ],
  formFields: [
    { key: "title", label: "Title", type: "text", required: true },
    { key: "class_name", label: "Class", type: "text", required: true },
    { key: "section", label: "Section", type: "text" },
    { key: "subject", label: "Subject", type: "text" },
    { key: "due_date", label: "Due Date (YYYY-MM-DD)", type: "date" },
    { key: "description", label: "Description", type: "textarea" },
    { key: "academic_year", label: "Academic Year", type: "text" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const onlineTestsModule: ModuleConfig = {
  key: "online_tests",
  title: "Online Tests",
  icon: "🖥️",
  feature: "online_tests",
  endpoint: "/online-tests",
  titleField: "title",
  subtitleField: "class_name",
  searchFields: ["title", "class_name", "subject"],
  listColumns: [
    { key: "class_name", label: "Class" },
    { key: "subject", label: "Subject" },
    { key: "duration_minutes", label: "Duration (min)" },
  ],
  formFields: [
    { key: "title", label: "Title", type: "text", required: true },
    { key: "class_name", label: "Class", type: "text", required: true },
    { key: "section", label: "Section", type: "text" },
    { key: "subject", label: "Subject", type: "text" },
    { key: "duration_minutes", label: "Duration (minutes)", type: "number" },
    { key: "description", label: "Description", type: "textarea" },
    { key: "academic_year", label: "Academic Year", type: "text" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const admissionsModule: ModuleConfig = {
  key: "admissions",
  title: "Admissions",
  icon: "🚪",
  feature: "admissions",
  endpoint: "/admissions",
  titleField: "student_name",
  subtitleField: "stage",
  searchFields: ["student_name", "inquiry_no", "grade_applying", "guardian_name"],
  listColumns: [
    { key: "grade_applying", label: "Grade" },
    { key: "stage", label: "Stage" },
    { key: "guardian_phone", label: "Guardian Phone" },
  ],
  formFields: [
    { key: "inquiry_no", label: "Inquiry No", type: "text", required: true },
    { key: "student_name", label: "Student Name", type: "text", required: true },
    { key: "grade_applying", label: "Grade Applying For", type: "text", required: true },
    { key: "academic_year", label: "Academic Year", type: "text", required: true },
    { key: "guardian_name", label: "Guardian Name", type: "text", required: true },
    { key: "guardian_phone", label: "Guardian Phone", type: "phone", required: true },
    { key: "guardian_email", label: "Guardian Email", type: "email" },
    { key: "source", label: "Source", type: "text" },
    { key: "stage", label: "Stage", type: "select", options: [
      { label: "Inquiry", value: "Inquiry" }, { label: "Assessment", value: "Assessment" },
      { label: "Offer", value: "Offer" }, { label: "Admitted", value: "Admitted" }, { label: "Rejected", value: "Rejected" },
    ] },
    { key: "follow_up_date", label: "Follow-up Date (YYYY-MM-DD)", type: "date" },
    { key: "assigned_to", label: "Assigned To", type: "text" },
    { key: "notes", label: "Notes", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: false,
};

export const communicationsModule: ModuleConfig = {
  key: "parent_communication",
  title: "Communications",
  icon: "📣",
  feature: "parent_communication",
  endpoint: "/communications/templates",
  titleField: "template_name",
  subtitleField: "channel",
  searchFields: ["template_name", "channel", "category", "audience"],
  listColumns: [
    { key: "channel", label: "Channel" },
    { key: "category", label: "Category" },
    { key: "status", label: "Status" },
  ],
  formFields: [
    { key: "template_name", label: "Template Name", type: "text", required: true },
    { key: "channel", label: "Channel", type: "select", options: [
      { label: "WhatsApp", value: "WhatsApp" }, { label: "SMS", value: "SMS" }, { label: "Email", value: "Email" },
    ] },
    { key: "category", label: "Category", type: "text", required: true },
    { key: "audience", label: "Audience", type: "text" },
    { key: "subject", label: "Subject", type: "text" },
    { key: "body", label: "Message Body", type: "textarea", required: true },
    { key: "language", label: "Language", type: "text" },
    { key: "status", label: "Status", type: "select", options: [
      { label: "Active", value: "Active" }, { label: "Inactive", value: "Inactive" },
    ] },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const studentServicesModule: ModuleConfig = {
  key: "student_services",
  title: "Student Services",
  icon: "🎫",
  feature: "student_services",
  endpoint: "/student-services",
  titleField: "subject",
  subtitleField: "category",
  searchFields: ["subject", "ticket_no", "requester_name", "category"],
  listColumns: [
    { key: "category", label: "Category" },
    { key: "priority", label: "Priority" },
    { key: "status", label: "Status" },
  ],
  formFields: [
    { key: "ticket_no", label: "Ticket No", type: "text", required: true },
    { key: "requester_name", label: "Requester Name", type: "text", required: true },
    { key: "requester_role", label: "Requester Role", type: "text" },
    { key: "contact_phone", label: "Contact Phone", type: "phone" },
    { key: "contact_email", label: "Contact Email", type: "email" },
    { key: "category", label: "Category", type: "text", required: true },
    { key: "priority", label: "Priority", type: "select", options: [
      { label: "Low", value: "Low" }, { label: "Medium", value: "Medium" }, { label: "High", value: "High" }, { label: "Urgent", value: "Urgent" },
    ] },
    { key: "subject", label: "Subject", type: "text", required: true },
    { key: "description", label: "Description", type: "textarea", required: true },
    { key: "assigned_to", label: "Assigned To", type: "text" },
    { key: "due_date", label: "Due Date (YYYY-MM-DD)", type: "date" },
    { key: "status", label: "Status", type: "select", options: [
      { label: "Open", value: "Open" }, { label: "In Progress", value: "In Progress" }, { label: "Closed", value: "Closed" },
    ] },
    { key: "resolution", label: "Resolution", type: "textarea" },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const counselingModule: ModuleConfig = {
  key: "counseling",
  title: "Counseling",
  icon: "🧠",
  feature: "counseling",
  endpoint: "/counseling",
  titleField: "concern_type",
  subtitleField: "risk_level",
  searchFields: ["case_no", "concern_type", "counselor"],
  listColumns: [
    { key: "risk_level", label: "Risk" },
    { key: "status", label: "Status" },
    { key: "session_date", label: "Session Date" },
  ],
  formFields: [
    { key: "case_no", label: "Case No", type: "text", required: true },
    { key: "student_id", label: "Student ID", type: "number", required: true },
    { key: "concern_type", label: "Concern Type", type: "text", required: true },
    { key: "risk_level", label: "Risk Level", type: "select", options: [
      { label: "Low", value: "Low" }, { label: "Medium", value: "Medium" }, { label: "High", value: "High" },
    ] },
    { key: "reported_by", label: "Reported By", type: "text" },
    { key: "counselor", label: "Counselor", type: "text" },
    { key: "session_date", label: "Session Date (YYYY-MM-DD)", type: "date" },
    { key: "next_follow_up_date", label: "Next Follow-up (YYYY-MM-DD)", type: "date" },
    { key: "action_plan", label: "Action Plan", type: "textarea" },
    { key: "status", label: "Status", type: "select", options: [
      { label: "Open", value: "Open" }, { label: "Closed", value: "Closed" },
    ] },
    { key: "outcome", label: "Outcome", type: "textarea" },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const enrichmentModule: ModuleConfig = {
  key: "enrichment",
  title: "Enrichment",
  icon: "🎨",
  feature: "enrichment",
  endpoint: "/enrichment",
  titleField: "activity_name",
  subtitleField: "activity_type",
  searchFields: ["activity_name", "activity_code", "activity_type", "coordinator"],
  listColumns: [
    { key: "activity_type", label: "Type" },
    { key: "status", label: "Status" },
    { key: "start_date", label: "Starts" },
  ],
  formFields: [
    { key: "activity_code", label: "Activity Code", type: "text", required: true },
    { key: "activity_name", label: "Activity Name", type: "text", required: true },
    { key: "activity_type", label: "Activity Type", type: "text", required: true },
    { key: "category", label: "Category", type: "text" },
    { key: "coordinator", label: "Coordinator", type: "text" },
    { key: "start_date", label: "Start Date (YYYY-MM-DD)", type: "date" },
    { key: "end_date", label: "End Date (YYYY-MM-DD)", type: "date" },
    { key: "venue", label: "Venue", type: "text" },
    { key: "eligible_classes", label: "Eligible Classes", type: "text" },
    { key: "capacity", label: "Capacity", type: "number" },
    { key: "fee_amount", label: "Fee Amount", type: "number" },
    { key: "status", label: "Status", type: "select", options: [
      { label: "Planned", value: "Planned" }, { label: "Ongoing", value: "Ongoing" }, { label: "Completed", value: "Completed" },
    ] },
    { key: "description", label: "Description", type: "textarea" },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const complianceModule: ModuleConfig = {
  key: "compliance",
  title: "Compliance",
  icon: "📋",
  feature: "compliance",
  endpoint: "/compliance",
  titleField: "requirement",
  subtitleField: "standard_area",
  searchFields: ["task_code", "requirement", "accreditation_body", "standard_area"],
  listColumns: [
    { key: "accreditation_body", label: "Body" },
    { key: "risk_level", label: "Risk" },
    { key: "status", label: "Status" },
  ],
  formFields: [
    { key: "task_code", label: "Task Code", type: "text", required: true },
    { key: "accreditation_body", label: "Accreditation Body", type: "text", required: true },
    { key: "standard_area", label: "Standard Area", type: "text", required: true },
    { key: "requirement", label: "Requirement", type: "textarea", required: true },
    { key: "owner", label: "Owner", type: "text" },
    { key: "due_date", label: "Due Date (YYYY-MM-DD)", type: "date" },
    { key: "review_date", label: "Review Date (YYYY-MM-DD)", type: "date" },
    { key: "risk_level", label: "Risk Level", type: "select", options: [
      { label: "Low", value: "Low" }, { label: "Medium", value: "Medium" }, { label: "High", value: "High" },
    ] },
    { key: "status", label: "Status", type: "select", options: [
      { label: "Open", value: "Open" }, { label: "In Progress", value: "In Progress" }, { label: "Completed", value: "Completed" },
    ] },
    { key: "finding", label: "Finding", type: "textarea" },
    { key: "action_plan", label: "Action Plan", type: "textarea" },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const internationalDocumentsModule: ModuleConfig = {
  key: "international_documents",
  title: "Int'l Documents",
  icon: "🛂",
  feature: "international_documents",
  endpoint: "/international-documents",
  titleField: "document_type",
  subtitleField: "status",
  searchFields: ["document_type", "document_no", "issuing_country"],
  listColumns: [
    { key: "status", label: "Status" },
    { key: "issue_date", label: "Issued" },
    { key: "expiry_date", label: "Expires" },
  ],
  formFields: [
    { key: "student_id", label: "Student ID", type: "number", required: true },
    { key: "document_type", label: "Document Type", type: "text", required: true },
    { key: "document_no", label: "Document No", type: "text" },
    { key: "issue_date", label: "Issue Date (YYYY-MM-DD)", type: "date" },
    { key: "expiry_date", label: "Expiry Date (YYYY-MM-DD)", type: "date" },
    { key: "issuing_country", label: "Issuing Country", type: "text" },
    { key: "status", label: "Status", type: "select", options: [
      { label: "Pending", value: "Pending" }, { label: "Verified", value: "Verified" }, { label: "Expired", value: "Expired" },
    ] },
    { key: "verified_by", label: "Verified By", type: "text" },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const multiCurriculumModule: ModuleConfig = {
  key: "multi_curriculum",
  title: "Multi-Curriculum",
  icon: "🌐",
  feature: "multi_curriculum",
  endpoint: "/multi-curriculum",
  titleField: "program_name",
  subtitleField: "curriculum_track",
  searchFields: ["program_name", "curriculum_track", "grade_level"],
  listColumns: [
    { key: "curriculum_track", label: "Track" },
    { key: "grade_level", label: "Grade" },
    { key: "status", label: "Status" },
  ],
  formFields: [
    { key: "program_name", label: "Program Name", type: "text", required: true },
    { key: "curriculum_track", label: "Curriculum Track", type: "text", required: true },
    { key: "grade_level", label: "Grade Level", type: "text", required: true },
    { key: "academic_year", label: "Academic Year", type: "text", required: true },
    { key: "subject_groups", label: "Subject Groups", type: "text" },
    { key: "assessment_model", label: "Assessment Model", type: "text" },
    { key: "coordinator", label: "Coordinator", type: "text" },
    { key: "status", label: "Status", type: "select", options: [
      { label: "Draft", value: "Draft" }, { label: "Active", value: "Active" }, { label: "Archived", value: "Archived" },
    ] },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const academicYearsModule: ModuleConfig = {
  key: "academic_years",
  title: "Academic Years",
  icon: "📅",
  feature: "academic_years",
  endpoint: "/academic-years",
  titleField: "name",
  subtitleField: "start_date",
  searchFields: ["name"],
  listColumns: [
    { key: "start_date", label: "Start" },
    { key: "end_date", label: "End" },
  ],
  formFields: [
    { key: "name", label: "Name", type: "text", required: true },
    { key: "start_date", label: "Start Date (YYYY-MM-DD)", type: "date" },
    { key: "end_date", label: "End Date (YYYY-MM-DD)", type: "date" },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const hostelModule: ModuleConfig = {
  key: "hostel",
  title: "Hostel",
  icon: "🏠",
  feature: "hostel",
  endpoint: "/hostel/blocks",
  titleField: "block_name",
  subtitleField: "hostel_type",
  searchFields: ["block_name", "hostel_type", "warden_name"],
  listColumns: [
    { key: "hostel_type", label: "Type" },
    { key: "warden_name", label: "Warden" },
    { key: "warden_phone", label: "Phone" },
  ],
  formFields: [
    { key: "block_name", label: "Block Name", type: "text", required: true },
    { key: "hostel_type", label: "Hostel Type", type: "select", options: [
      { label: "Boys", value: "Boys" }, { label: "Girls", value: "Girls" },
    ] },
    { key: "warden_name", label: "Warden Name", type: "text" },
    { key: "warden_phone", label: "Warden Phone", type: "phone" },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const transportModule: ModuleConfig = {
  key: "transport",
  title: "Transport",
  icon: "🚌",
  feature: "transport",
  endpoint: "/transport/routes",
  titleField: "route_name",
  subtitleField: "start_point",
  searchFields: ["route_name", "start_point", "end_point"],
  listColumns: [
    { key: "start_point", label: "From" },
    { key: "end_point", label: "To" },
    { key: "monthly_fee", label: "Monthly Fee" },
  ],
  formFields: [
    { key: "route_name", label: "Route Name", type: "text", required: true },
    { key: "start_point", label: "Start Point", type: "text" },
    { key: "end_point", label: "End Point", type: "text" },
    { key: "monthly_fee", label: "Monthly Fee", type: "number" },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const healthInfirmaryModule: ModuleConfig = {
  key: "health_infirmary",
  title: "Health Infirmary",
  icon: "🩺",
  feature: "health_infirmary",
  endpoint: "/health-infirmary/visits",
  titleField: "symptoms",
  subtitleField: "status",
  searchFields: ["symptoms", "diagnosis", "attended_by"],
  listColumns: [
    { key: "visit_date", label: "Date" },
    { key: "status", label: "Status" },
  ],
  formFields: [
    { key: "student_id", label: "Student ID", type: "number", required: true },
    { key: "visit_date", label: "Visit Date (YYYY-MM-DD)", type: "date", required: true },
    { key: "visit_time", label: "Visit Time (HH:MM)", type: "text" },
    { key: "symptoms", label: "Symptoms", type: "textarea", required: true },
    { key: "diagnosis", label: "Diagnosis", type: "textarea" },
    { key: "treatment", label: "Treatment", type: "textarea" },
    { key: "medicine_given", label: "Medicine Given", type: "text" },
    { key: "attended_by", label: "Attended By", type: "text" },
    { key: "follow_up_date", label: "Follow-up Date (YYYY-MM-DD)", type: "date" },
    { key: "status", label: "Status", type: "select", options: [
      { label: "Open", value: "Open" }, { label: "Closed", value: "Closed" },
    ] },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const messModule: ModuleConfig = {
  key: "mess_management",
  title: "Mess Management",
  icon: "🍽️",
  feature: "mess_management",
  endpoint: "/mess/menus",
  titleField: "meal_type",
  subtitleField: "menu_date",
  searchFields: ["meal_type", "menu_items"],
  listColumns: [
    { key: "menu_date", label: "Date" },
    { key: "meal_type", label: "Meal" },
    { key: "is_published", label: "Published" },
  ],
  formFields: [
    { key: "menu_date", label: "Menu Date (YYYY-MM-DD)", type: "date", required: true },
    { key: "meal_type", label: "Meal Type", type: "select", required: true, options: [
      { label: "Breakfast", value: "Breakfast" }, { label: "Lunch", value: "Lunch" }, { label: "Snacks", value: "Snacks" }, { label: "Dinner", value: "Dinner" },
    ] },
    { key: "menu_items", label: "Menu Items", type: "textarea", required: true },
    { key: "nutrition_notes", label: "Nutrition Notes", type: "textarea" },
    { key: "allergen_notes", label: "Allergen Notes", type: "textarea" },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const libraryModule: ModuleConfig = {
  key: "library",
  title: "Library",
  icon: "📖",
  feature: "library",
  endpoint: "/library/books",
  titleField: "title",
  subtitleField: "author",
  searchFields: ["title", "author", "accession_no", "isbn"],
  listColumns: [
    { key: "category", label: "Category" },
    { key: "available_copies", label: "Available" },
    { key: "status", label: "Status" },
  ],
  formFields: [
    { key: "accession_no", label: "Accession No", type: "text", required: true },
    { key: "title", label: "Title", type: "text", required: true },
    { key: "author", label: "Author", type: "text" },
    { key: "category", label: "Category", type: "text" },
    { key: "publisher", label: "Publisher", type: "text" },
    { key: "isbn", label: "ISBN", type: "text" },
    { key: "total_copies", label: "Total Copies", type: "number" },
    { key: "available_copies", label: "Available Copies", type: "number" },
    { key: "shelf_no", label: "Shelf No", type: "text" },
    { key: "status", label: "Status", type: "select", options: [
      { label: "Available", value: "Available" }, { label: "Unavailable", value: "Unavailable" },
    ] },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const inventoryModule: ModuleConfig = {
  key: "inventory",
  title: "Inventory",
  icon: "📦",
  feature: "inventory",
  endpoint: "/inventory/items",
  titleField: "item_name",
  subtitleField: "category",
  searchFields: ["item_name", "item_code", "category"],
  listColumns: [
    { key: "quantity_available", label: "Available" },
    { key: "reorder_level", label: "Reorder Level" },
    { key: "status", label: "Status" },
  ],
  formFields: [
    { key: "item_name", label: "Item Name", type: "text", required: true },
    { key: "item_code", label: "Item Code", type: "text" },
    { key: "category", label: "Category", type: "text" },
    { key: "unit", label: "Unit", type: "text" },
    { key: "quantity_available", label: "Quantity Available", type: "number" },
    { key: "reorder_level", label: "Reorder Level", type: "number" },
    { key: "unit_price", label: "Unit Price", type: "number" },
    { key: "location", label: "Location", type: "text" },
    { key: "status", label: "Status", type: "select", options: [
      { label: "Active", value: "Active" }, { label: "Inactive", value: "Inactive" },
    ] },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const alumniWithdrawalsModule: ModuleConfig = {
  key: "alumni_withdrawals",
  title: "Alumni & Exit",
  icon: "🎓",
  feature: "alumni_withdrawals",
  endpoint: "/alumni-withdrawals",
  titleField: "student_name",
  subtitleField: "record_type",
  searchFields: ["student_name", "record_no", "admission_no"],
  listColumns: [
    { key: "record_type", label: "Type" },
    { key: "last_class", label: "Last Class" },
    { key: "current_status", label: "Status" },
  ],
  formFields: [
    { key: "record_no", label: "Record No", type: "text", required: true },
    { key: "student_name", label: "Student Name", type: "text", required: true },
    { key: "admission_no", label: "Admission No", type: "text" },
    { key: "last_class", label: "Last Class", type: "text" },
    { key: "record_type", label: "Record Type", type: "select", options: [
      { label: "Withdrawal", value: "Withdrawal" }, { label: "Graduation", value: "Graduation" }, { label: "Transfer", value: "Transfer" },
    ] },
    { key: "request_date", label: "Request Date (YYYY-MM-DD)", type: "date" },
    { key: "leaving_date", label: "Leaving Date (YYYY-MM-DD)", type: "date" },
    { key: "reason", label: "Reason", type: "textarea", required: true },
    { key: "destination_school", label: "Destination School", type: "text" },
    { key: "destination_country", label: "Destination Country", type: "text" },
    { key: "certificate_status", label: "Certificate Status", type: "text" },
    { key: "alumni_email", label: "Alumni Email", type: "email" },
    { key: "alumni_phone", label: "Alumni Phone", type: "phone" },
    { key: "current_status", label: "Current Status", type: "text" },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const masterDataModule: ModuleConfig = {
  key: "master_data",
  title: "Master Data",
  icon: "🗂️",
  feature: "master_data",
  endpoint: "/master-data",
  titleField: "value",
  subtitleField: "category",
  searchFields: ["value", "category"],
  listColumns: [
    { key: "category", label: "Category" },
    { key: "sort_order", label: "Sort Order" },
  ],
  formFields: [
    { key: "category", label: "Category", type: "text", required: true },
    { key: "value", label: "Value", type: "text", required: true },
    { key: "sort_order", label: "Sort Order", type: "number" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const usersModule: ModuleConfig = {
  key: "users",
  title: "User Management",
  icon: "👤",
  feature: "users",
  endpoint: "/users",
  titleField: "name",
  subtitleField: "role",
  searchFields: ["name", "email", "role"],
  listColumns: [
    { key: "email", label: "Email" },
    { key: "role", label: "Role" },
  ],
  formFields: [
    { key: "name", label: "Full Name", type: "text", required: true },
    { key: "email", label: "Email", type: "email", required: true },
    { key: "password", label: "Password", type: "text", required: true },
    { key: "role", label: "Role", type: "select", required: true, options: [
      { label: "Admin", value: "Admin" },
      { label: "Principal", value: "Principal" },
      { label: "Accounts", value: "Accounts" },
      { label: "Teacher", value: "Teacher" },
      { label: "Parent", value: "Parent" },
      { label: "Student", value: "Student" },
    ] },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const staffModules: ModuleConfig[] = [
  studentsModule,
  teachersModule,
  classesModule,
  examsModule,
  feesModule,
  accountingModule,
  timetableModule,
  homeworkModule,
  onlineTestsModule,
  admissionsModule,
  communicationsModule,
  studentServicesModule,
  counselingModule,
  enrichmentModule,
  complianceModule,
  internationalDocumentsModule,
  multiCurriculumModule,
  academicYearsModule,
  hostelModule,
  transportModule,
  healthInfirmaryModule,
  messModule,
  libraryModule,
  inventoryModule,
  alumniWithdrawalsModule,
  masterDataModule,
  usersModule,
];
