import { ModuleConfig } from "./types";
import * as generated from "./generated";

export const studentsModule: ModuleConfig = {
  key: "students",
  title: "Students",
  icon: "St",
  group: "Students",
  feature: "students",
  endpoint: "/students",
  titleField: "first_name",
  subtitleField: "class_name",
  searchFields: ["first_name", "last_name", "admission_no", "roll_no"],
  listColumns: [
    { key: "admission_no", label: "Admission No" },
    { key: "class_name", label: "Class" },
    { key: "section", label: "Section" },
    { key: "student_status", label: "Status" },
  ],
  formFields: [
    { key: "admission_no", label: "Admission No", type: "text", required: true },
    { key: "first_name", label: "First Name", type: "text", required: true },
    { key: "last_name", label: "Last Name", type: "text" },
    { key: "gender", label: "Gender", type: "select", options: [
      { label: "Male", value: "Male" }, { label: "Female", value: "Female" }, { label: "Other", value: "Other" },
    ] },
    { key: "dob", label: "Date of Birth (YYYY-MM-DD)", type: "date" },
    { key: "class_name", label: "Class", type: "text" },
    { key: "section", label: "Section", type: "text" },
    { key: "house", label: "House", type: "text" },
    { key: "admission_date", label: "Admission Date (YYYY-MM-DD)", type: "date" },
    { key: "student_status", label: "Status", type: "select", options: [
      { label: "Active", value: "Active" }, { label: "Inactive", value: "Inactive" },
    ] },
    { key: "residential_type", label: "Residential Type", type: "select", options: [
      { label: "Day Scholar", value: "Day Scholar" }, { label: "Hosteller", value: "Hosteller" },
    ] },
    { key: "father_name", label: "Father's Name", type: "text" },
    { key: "mother_name", label: "Mother's Name", type: "text" },
    { key: "guardian_name", label: "Guardian Name", type: "text" },
    { key: "guardian_phone", label: "Guardian Phone", type: "phone" },
    { key: "guardian_email", label: "Guardian Email", type: "email" },
    { key: "blood_group", label: "Blood Group", type: "text" },
    { key: "photo_url", label: "Photo", type: "photo" },
    { key: "medical_notes", label: "Medical Notes", type: "textarea" },
    { key: "allergies", label: "Allergies", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const teachersModule: ModuleConfig = {
  key: "teachers",
  title: "Teachers",
  icon: "Te",
  group: "People & Access",
  feature: "teachers",
  endpoint: "/teachers",
  titleField: "name",
  subtitleField: "department",
  searchFields: ["name", "employee_no", "email", "subject"],
  listColumns: [
    { key: "employee_no", label: "Employee No" },
    { key: "subject", label: "Subject" },
    { key: "assigned_class", label: "Assigned Class" },
  ],
  formFields: [
    { key: "employee_no", label: "Employee No", type: "text", required: true },
    { key: "name", label: "Full Name", type: "text", required: true },
    { key: "email", label: "Email", type: "email" },
    { key: "phone", label: "Phone", type: "phone" },
    { key: "gender", label: "Gender", type: "select", options: [
      { label: "Male", value: "Male" }, { label: "Female", value: "Female" }, { label: "Other", value: "Other" },
    ] },
    { key: "department", label: "Department", type: "text" },
    { key: "subject", label: "Subject", type: "text" },
    { key: "assigned_class", label: "Assigned Class", type: "text" },
    { key: "qualification", label: "Qualification", type: "text" },
    { key: "joining_date", label: "Joining Date (YYYY-MM-DD)", type: "date" },
    { key: "employment_type", label: "Employment Type", type: "text" },
    { key: "salary_grade", label: "Salary Grade", type: "text" },
    { key: "address", label: "Address", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const classesModule: ModuleConfig = {
  key: "classes",
  title: "Classes",
  icon: "Cl",
  group: "Academics",
  feature: "classes",
  endpoint: "/classes",
  titleField: "class_name",
  subtitleField: "section",
  searchFields: ["class_name", "section", "class_teacher"],
  listColumns: [
    { key: "section", label: "Section" },
    { key: "class_teacher", label: "Class Teacher" },
    { key: "room_no", label: "Room" },
  ],
  formFields: [
    { key: "class_name", label: "Class Name", type: "text", required: true },
    { key: "section", label: "Section", type: "text", required: true },
    { key: "class_teacher", label: "Class Teacher", type: "text" },
    { key: "academic_year", label: "Academic Year", type: "text" },
    { key: "room_no", label: "Room No", type: "text" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const examsModule: ModuleConfig = {
  key: "exams",
  title: "Exams",
  icon: "Ex",
  group: "Academics",
  feature: "exams",
  endpoint: "/exams",
  titleField: "exam_name",
  subtitleField: "exam_type",
  searchFields: ["exam_name", "exam_type", "class_name"],
  listColumns: [
    { key: "class_name", label: "Class" },
    { key: "section", label: "Section" },
    { key: "exam_date", label: "Date" },
  ],
  formFields: [
    { key: "exam_name", label: "Exam Name", type: "text", required: true },
    { key: "exam_type", label: "Exam Type", type: "text" },
    { key: "class_name", label: "Class", type: "text" },
    { key: "section", label: "Section", type: "text" },
    { key: "exam_date", label: "Exam Date (YYYY-MM-DD)", type: "date" },
    { key: "academic_year", label: "Academic Year", type: "text" },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const feesModule: ModuleConfig = {
  key: "fees",
  title: "Fees",
  icon: "Fe",
  group: "Finance & Operations",
  feature: "fees",
  endpoint: "/fees",
  titleField: "fee_type",
  subtitleField: "payment_status",
  searchFields: ["fee_type", "receipt_no", "payment_status"],
  listColumns: [
    { key: "total_amount", label: "Total" },
    { key: "paid_amount", label: "Paid" },
    { key: "due_amount", label: "Due" },
    { key: "payment_status", label: "Status" },
  ],
  formFields: [
    {
      key: "student_id",
      label: "Student",
      type: "reference",
      required: true,
      reference: {
        endpoint: "/students",
        searchFields: ["first_name", "last_name", "admission_no"],
        labelFields: ["first_name", "last_name"],
        subtitleFields: ["admission_no", "class_name"],
      },
    },
    { key: "fee_type", label: "Fee Type", type: "text", required: true },
    { key: "total_amount", label: "Total Amount", type: "number", required: true },
    { key: "paid_amount", label: "Paid Amount", type: "number" },
    { key: "due_date", label: "Due Date (YYYY-MM-DD)", type: "date" },
    { key: "payment_date", label: "Payment Date (YYYY-MM-DD)", type: "date" },
    { key: "receipt_no", label: "Receipt No", type: "text" },
    { key: "academic_year", label: "Academic Year", type: "text" },
    { key: "remarks", label: "Remarks", type: "textarea" },
  ],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const staffModules: ModuleConfig[] = [
  studentsModule,
  teachersModule,
  classesModule,
  examsModule,
  feesModule,
  ...Object.values(generated).filter((m): m is ModuleConfig => typeof m === "object" && m !== null && "endpoint" in m),
];
