// AUTO-DERIVED from the deployed OpenAPI schema, then curated.
// Field shapes mirror what the backend accepts; titles/icons/groups/features are hand-set.
import { ModuleConfig } from "./types";

export const subjectsModule: ModuleConfig = {
  key: "subjects",
  title: "Subjects",
  icon: "Sb",
  group: "Academics",
  feature: "master_data",
  roles: ["Admin", "Principal", "Teacher"],
  endpoint: "/subjects",
  titleField: "subject_name",
  subtitleField: "subject_code",
  searchFields: ["subject_name", "subject_code", "subject_type"],
  listColumns: [{"key": "subject_type", "label": "Subject Type"}, {"key": "is_active", "label": "Is Active"}],
  formFields: [{"key": "subject_code", "label": "Subject Code", "type": "text", "required": true}, {"key": "subject_name", "label": "Subject Name", "type": "lookup", "lookup": {"endpoint": "/subjects", "valueField": "subject_name", "searchFields": ["subject_name", "subject_code"], "subtitleFields": ["subject_code"]}, "required": true}, {"key": "subject_type", "label": "Subject Type", "type": "masterSelect", "masterCategory": "Subject"}, {"key": "is_active", "label": "Is Active", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const classSubjectsModule: ModuleConfig = {
  key: "classSubjects",
  title: "Class Subjects",
  icon: "Cs",
  group: "Academics",
  feature: "classes",
  endpoint: "/class-subjects",
  titleField: "subject_name",
  subtitleField: "academic_year",
  searchFields: ["subject_name", "academic_year"],
  listColumns: [{"key": "class_id", "label": "Class ID"}, {"key": "subject_id", "label": "Subject ID"}, {"key": "teacher_id", "label": "Teacher ID"}, {"key": "weekly_periods", "label": "Weekly Periods"}],
  formFields: [{"key": "class_id", "label": "Class ID", "type": "reference", "reference": {"endpoint": "/classes", "searchFields": ["class_name", "section"], "labelFields": ["class_name", "section"], "subtitleFields": ["class_teacher"]}, "required": true}, {"key": "subject_id", "label": "Subject ID", "type": "reference", "reference": {"endpoint": "/subjects", "searchFields": ["subject_name", "subject_code"], "labelFields": ["subject_name"], "subtitleFields": ["subject_code"]}}, {"key": "subject_name", "label": "Subject Name", "type": "lookup", "lookup": {"endpoint": "/subjects", "valueField": "subject_name", "searchFields": ["subject_name", "subject_code"], "subtitleFields": ["subject_code"]}}, {"key": "academic_year", "label": "Academic Year", "type": "masterSelect", "masterCategory": "AcademicYear"}, {"key": "teacher_id", "label": "Teacher ID", "type": "reference", "reference": {"endpoint": "/teachers", "searchFields": ["name", "employee_no"], "labelFields": ["name"], "subtitleFields": ["employee_no", "department"]}}, {"key": "weekly_periods", "label": "Weekly Periods", "type": "number"}, {"key": "is_active", "label": "Is Active", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const timetableModule: ModuleConfig = {
  key: "timetable",
  title: "Timetable",
  icon: "Tt",
  group: "Academics",
  feature: "timetable",
  endpoint: "/timetable",
  titleField: "label",
  subtitleField: "academic_year",
  searchFields: ["label", "academic_year", "class_name_snapshot", "section_snapshot"],
  listColumns: [{"key": "class_id", "label": "Class ID"}, {"key": "class_name_snapshot", "label": "Class Name Snapshot"}, {"key": "section_snapshot", "label": "Section Snapshot"}, {"key": "day_of_week", "label": "Day Of Week"}],
  formFields: [{"key": "academic_year", "label": "Academic Year", "type": "masterSelect", "masterCategory": "AcademicYear"}, {"key": "class_id", "label": "Class ID", "type": "reference", "reference": {"endpoint": "/classes", "searchFields": ["class_name", "section"], "labelFields": ["class_name", "section"], "subtitleFields": ["class_teacher"]}}, {"key": "class_name_snapshot", "label": "Class Name Snapshot", "type": "lookup", "lookup": {"endpoint": "/classes", "valueField": "class_name", "searchFields": ["class_name", "section"], "subtitleFields": ["section"]}}, {"key": "section_snapshot", "label": "Section Snapshot", "type": "lookup", "lookup": {"endpoint": "/classes", "valueField": "section", "searchFields": ["section", "class_name"], "subtitleFields": ["class_name"]}}, {"key": "day_of_week", "label": "Day Of Week", "type": "select", "options": [{"label": "Monday", "value": "Monday"}, {"label": "Tuesday", "value": "Tuesday"}, {"label": "Wednesday", "value": "Wednesday"}, {"label": "Thursday", "value": "Thursday"}, {"label": "Friday", "value": "Friday"}, {"label": "Saturday", "value": "Saturday"}, {"label": "Sunday", "value": "Sunday"}], "required": true}, {"key": "period_no", "label": "Period No.", "type": "number", "required": true}, {"key": "entry_type", "label": "Entry Type", "type": "select", "options": [{"label": "period", "value": "period"}, {"label": "break", "value": "break"}, {"label": "assembly", "value": "assembly"}, {"label": "activity", "value": "activity"}]}, {"key": "label", "label": "Label", "type": "text"}, {"key": "duration_min", "label": "Duration Min", "type": "number"}, {"key": "start_time", "label": "Start Time", "type": "time"}, {"key": "end_time", "label": "End Time", "type": "time"}, {"key": "subject", "label": "Subject", "type": "lookup", "lookup": {"endpoint": "/subjects", "valueField": "subject_name", "searchFields": ["subject_name", "subject_code"], "subtitleFields": ["subject_code"]}}, {"key": "teacher_id", "label": "Teacher ID", "type": "reference", "reference": {"endpoint": "/teachers", "searchFields": ["name", "employee_no"], "labelFields": ["name"], "subtitleFields": ["employee_no", "department"]}}, {"key": "teacher_name_snapshot", "label": "Teacher Name Snapshot", "type": "lookup", "lookup": {"endpoint": "/teachers", "valueField": "name", "searchFields": ["name", "employee_no"], "subtitleFields": ["employee_no", "department"]}}, {"key": "room", "label": "Room", "type": "text"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const homeworkModule: ModuleConfig = {
  key: "homework",
  title: "Homework",
  icon: "Hw",
  group: "Academics",
  feature: "homework",
  endpoint: "/homework",
  titleField: "title",
  subtitleField: "academic_year",
  searchFields: ["title", "academic_year", "class_name", "section"],
  listColumns: [{"key": "class_name", "label": "Class Name"}, {"key": "section", "label": "Section"}, {"key": "subject", "label": "Subject"}, {"key": "description", "label": "Description"}],
  formFields: [{"key": "academic_year", "label": "Academic Year", "type": "masterSelect", "masterCategory": "AcademicYear"}, {"key": "class_name", "label": "Class Name", "type": "lookup", "lookup": {"endpoint": "/classes", "valueField": "class_name", "searchFields": ["class_name", "section"], "subtitleFields": ["section", "class_teacher"]}, "required": true}, {"key": "section", "label": "Section", "type": "lookup", "lookup": {"endpoint": "/classes", "valueField": "section", "searchFields": ["section", "class_name"], "subtitleFields": ["class_name"]}}, {"key": "subject", "label": "Subject", "type": "lookup", "lookup": {"endpoint": "/subjects", "valueField": "subject_name", "searchFields": ["subject_name", "subject_code"], "subtitleFields": ["subject_code"]}}, {"key": "title", "label": "Title", "type": "text", "required": true}, {"key": "description", "label": "Description", "type": "textarea"}, {"key": "due_date", "label": "Due Date", "type": "date"}, {"key": "attachment_url", "label": "Attachment URL", "type": "photo"}, {"key": "teacher_id", "label": "Teacher ID", "type": "reference", "reference": {"endpoint": "/teachers", "searchFields": ["name", "employee_no"], "labelFields": ["name"], "subtitleFields": ["employee_no", "department"]}}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const onlineTestsModule: ModuleConfig = {
  key: "onlineTests",
  title: "Online Tests",
  icon: "Ot",
  group: "Academics",
  feature: "online_tests",
  endpoint: "/online-tests",
  titleField: "title",
  subtitleField: "academic_year",
  searchFields: ["title", "academic_year", "class_name", "section"],
  listColumns: [{"key": "class_name", "label": "Class Name"}, {"key": "section", "label": "Section"}, {"key": "subject", "label": "Subject"}, {"key": "description", "label": "Description"}],
  formFields: [{"key": "academic_year", "label": "Academic Year", "type": "masterSelect", "masterCategory": "AcademicYear"}, {"key": "class_name", "label": "Class Name", "type": "lookup", "lookup": {"endpoint": "/classes", "valueField": "class_name", "searchFields": ["class_name", "section"], "subtitleFields": ["section", "class_teacher"]}, "required": true}, {"key": "section", "label": "Section", "type": "lookup", "lookup": {"endpoint": "/classes", "valueField": "section", "searchFields": ["section", "class_name"], "subtitleFields": ["class_name"]}}, {"key": "subject", "label": "Subject", "type": "lookup", "lookup": {"endpoint": "/subjects", "valueField": "subject_name", "searchFields": ["subject_name", "subject_code"], "subtitleFields": ["subject_code"]}}, {"key": "title", "label": "Title", "type": "text", "required": true}, {"key": "description", "label": "Description", "type": "textarea"}, {"key": "duration_minutes", "label": "Duration Minutes", "type": "number"}, {"key": "starts_at", "label": "Starts At", "type": "text"}, {"key": "ends_at", "label": "Ends At", "type": "text"}, {"key": "teacher_id", "label": "Teacher ID", "type": "reference", "reference": {"endpoint": "/teachers", "searchFields": ["name", "employee_no"], "labelFields": ["name"], "subtitleFields": ["employee_no", "department"]}}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const examTemplatesModule: ModuleConfig = {
  key: "examTemplates",
  title: "Exam Templates",
  icon: "Et",
  group: "Academics",
  feature: "exams",
  endpoint: "/exam-templates",
  titleField: "name",
  subtitleField: "exam_type",
  searchFields: ["name", "exam_type"],
  listColumns: [{"key": "next_run_date", "label": "Next Run Date"}, {"key": "is_active", "label": "Is Active"}, {"key": "remarks", "label": "Remarks"}],
  formFields: [{"key": "name", "label": "Name", "type": "text", "required": true}, {"key": "exam_type", "label": "Exam Type", "type": "masterSelect", "masterCategory": "ExamType"}, {"key": "next_run_date", "label": "Next Run Date", "type": "date"}, {"key": "is_active", "label": "Is Active", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const examComponentsModule: ModuleConfig = {
  key: "examComponents",
  title: "Exam Components",
  icon: "Ec",
  group: "Academics",
  feature: "exams",
  endpoint: "/exam-components",
  titleField: "component_name",
  searchFields: ["component_name"],
  listColumns: [{"key": "exam_id", "label": "Exam ID"}, {"key": "max_marks", "label": "Max Marks"}, {"key": "weightage", "label": "Weightage"}, {"key": "sort_order", "label": "Sort Order"}],
  formFields: [{"key": "exam_id", "label": "Exam ID", "type": "reference", "reference": {"endpoint": "/exams", "searchFields": ["exam_name", "exam_type"], "labelFields": ["exam_name"], "subtitleFields": ["class_name", "section"]}, "required": true}, {"key": "component_name", "label": "Component Name", "type": "text", "required": true}, {"key": "max_marks", "label": "Max Marks", "type": "number"}, {"key": "weightage", "label": "Weightage", "type": "number"}, {"key": "sort_order", "label": "Sort Order", "type": "number"}, {"key": "is_active", "label": "Is Active", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const classExamMappingsModule: ModuleConfig = {
  key: "classExamMappings",
  title: "Class Exam Mapping",
  icon: "Ce",
  group: "Academics",
  feature: "exams",
  endpoint: "/class-exam-mappings",
  titleField: "academic_year",
  searchFields: ["academic_year"],
  listColumns: [{"key": "class_id", "label": "Class ID"}, {"key": "exam_id", "label": "Exam ID"}, {"key": "exam_date", "label": "Exam Date"}, {"key": "is_active", "label": "Is Active"}],
  formFields: [{"key": "class_id", "label": "Class ID", "type": "reference", "reference": {"endpoint": "/classes", "searchFields": ["class_name", "section"], "labelFields": ["class_name", "section"], "subtitleFields": ["class_teacher"]}, "required": true}, {"key": "exam_id", "label": "Exam ID", "type": "reference", "reference": {"endpoint": "/exams", "searchFields": ["exam_name", "exam_type"], "labelFields": ["exam_name"], "subtitleFields": ["class_name", "section"]}, "required": true}, {"key": "academic_year", "label": "Academic Year", "type": "masterSelect", "masterCategory": "AcademicYear", "required": true}, {"key": "exam_date", "label": "Exam Date", "type": "date"}, {"key": "is_active", "label": "Is Active", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const academicYearsModule: ModuleConfig = {
  key: "academicYears",
  title: "Academic Years",
  icon: "Ay",
  group: "Academics",
  feature: "academic_years",
  endpoint: "/academic-years",
  titleField: "name",
  subtitleField: "auto_promote_to_year",
  searchFields: ["name", "auto_promote_to_year"],
  listColumns: [{"key": "start_date", "label": "Start Date"}, {"key": "end_date", "label": "End Date"}, {"key": "remarks", "label": "Remarks"}, {"key": "auto_promote_enabled", "label": "Auto Promote Enabled"}],
  formFields: [{"key": "name", "label": "Name", "type": "text", "required": true}, {"key": "start_date", "label": "Start Date", "type": "date"}, {"key": "end_date", "label": "End Date", "type": "date"}, {"key": "remarks", "label": "Remarks", "type": "textarea"}, {"key": "auto_promote_enabled", "label": "Auto Promote Enabled", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "auto_promote_date", "label": "Auto Promote Date", "type": "date"}, {"key": "auto_promote_to_year", "label": "Auto Promote To Year", "type": "masterSelect", "masterCategory": "AcademicYear"}, {"key": "auto_promote_carry_forward_fees", "label": "Auto Promote Carry Forward Fees", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const multiCurriculumModule: ModuleConfig = {
  key: "multiCurriculum",
  title: "Multi Curriculum",
  icon: "Cu",
  group: "Academics",
  feature: "multi_curriculum",
  endpoint: "/multi-curriculum",
  titleField: "program_name",
  subtitleField: "curriculum_track",
  searchFields: ["program_name", "curriculum_track", "grade_level", "academic_year"],
  listColumns: [{"key": "grade_level", "label": "Grade Level"}, {"key": "academic_year", "label": "Academic Year"}, {"key": "class_id", "label": "Class ID"}, {"key": "subject_groups", "label": "Subject Groups"}],
  formFields: [{"key": "program_name", "label": "Program Name", "type": "text", "required": true}, {"key": "curriculum_track", "label": "Curriculum Track", "type": "select", "options": [{"label": "IB PYP", "value": "IB PYP"}, {"label": "IB MYP", "value": "IB MYP"}, {"label": "IB DP", "value": "IB DP"}, {"label": "Cambridge Primary", "value": "Cambridge Primary"}, {"label": "Cambridge Lower Secondary", "value": "Cambridge Lower Secondary"}, {"label": "IGCSE", "value": "IGCSE"}, {"label": "A-Level", "value": "A-Level"}, {"label": "CBSE", "value": "CBSE"}, {"label": "ICSE", "value": "ICSE"}, {"label": "State Board", "value": "State Board"}, {"label": "Custom", "value": "Custom"}], "required": true}, {"key": "grade_level", "label": "Grade Level", "type": "lookup", "lookup": {"endpoint": "/classes", "valueField": "class_name", "searchFields": ["class_name"], "subtitleFields": ["section"]}, "required": true}, {"key": "academic_year", "label": "Academic Year", "type": "masterSelect", "masterCategory": "AcademicYear", "required": true}, {"key": "class_id", "label": "Class ID", "type": "reference", "reference": {"endpoint": "/classes", "searchFields": ["class_name", "section"], "labelFields": ["class_name", "section"], "subtitleFields": ["class_teacher"]}}, {"key": "subject_groups", "label": "Subject Groups", "type": "text"}, {"key": "assessment_model", "label": "Assessment Model", "type": "text"}, {"key": "coordinator", "label": "Coordinator", "type": "lookup", "lookup": {"endpoint": "/teachers", "valueField": "name", "searchFields": ["name", "employee_no"], "subtitleFields": ["department"]}}, {"key": "status", "label": "Status", "type": "select", "options": [{"label": "Draft", "value": "Draft"}, {"label": "Active", "value": "Active"}, {"label": "Archived", "value": "Archived"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const usersModule: ModuleConfig = {
  key: "users",
  title: "User Management",
  icon: "Us",
  group: "People & Access",
  feature: "users",
  endpoint: "/users",
  titleField: "name",
  subtitleField: "email",
  searchFields: ["name", "email", "password", "role"],
  listColumns: [{"key": "password", "label": "Password"}, {"key": "role", "label": "Role"}],
  formFields: [{"key": "name", "label": "Name", "type": "text", "required": true}, {"key": "email", "label": "Email", "type": "email", "required": true}, {"key": "password", "label": "Password", "type": "password", "required": true}, {"key": "role", "label": "Role", "type": "select", "options": [{"label": "Admin", "value": "Admin"}, {"label": "Principal", "value": "Principal"}, {"label": "Accounts", "value": "Accounts"}, {"label": "Teacher", "value": "Teacher"}, {"label": "Parent", "value": "Parent"}, {"label": "Student", "value": "Student"}], "required": true}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const rolesModule: ModuleConfig = {
  key: "roles",
  title: "Roles & Permissions",
  icon: "Rl",
  group: "People & Access",
  feature: "users",
  endpoint: "/roles",
  titleField: "name",
  searchFields: ["name"],
  listColumns: [{"key": "description", "label": "Description"}, {"key": "permissions", "label": "Permissions"}],
  formFields: [{"key": "name", "label": "Name", "type": "text", "required": true}, {"key": "description", "label": "Description", "type": "textarea"}, {"key": "permissions", "label": "Permissions", "type": "text", "required": true}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const studentEnrollmentsModule: ModuleConfig = {
  key: "studentEnrollments",
  title: "Student Enrollments",
  icon: "En",
  group: "Students",
  // `/student-enrollments` has no entry in the backend's path→feature map, so
// no permission grant can reach it — the role list below is what admits a
// user, exactly as on the web.
  feature: "student_enrollments",
  roles: ["Admin", "Principal", "Teacher"],
  endpoint: "/student-enrollments",
  titleField: "academic_year",
  subtitleField: "roll_no",
  searchFields: ["academic_year", "roll_no", "enrollment_status", "promotion_status"],
  listColumns: [{"key": "student_id", "label": "Student ID"}, {"key": "class_id", "label": "Class ID"}, {"key": "start_date", "label": "Start Date"}, {"key": "end_date", "label": "End Date"}],
  formFields: [{"key": "student_id", "label": "Student ID", "type": "reference", "reference": {"endpoint": "/students", "searchFields": ["first_name", "last_name", "admission_no"], "labelFields": ["first_name", "last_name"], "subtitleFields": ["admission_no", "class_name"]}, "required": true}, {"key": "class_id", "label": "Class ID", "type": "reference", "reference": {"endpoint": "/classes", "searchFields": ["class_name", "section"], "labelFields": ["class_name", "section"], "subtitleFields": ["class_teacher"]}, "required": true}, {"key": "academic_year", "label": "Academic Year", "type": "masterSelect", "masterCategory": "AcademicYear", "required": true}, {"key": "roll_no", "label": "Roll No.", "type": "text"}, {"key": "start_date", "label": "Start Date", "type": "date"}, {"key": "end_date", "label": "End Date", "type": "date"}, {"key": "enrollment_status", "label": "Enrollment Status", "type": "select", "options": [{"label": "Active", "value": "Active"}, {"label": "Completed", "value": "Completed"}, {"label": "Withdrawn", "value": "Withdrawn"}]}, {"key": "promotion_status", "label": "Promotion Status", "type": "select", "options": [{"label": "Not Promoted", "value": "Not Promoted"}, {"label": "Promoted", "value": "Promoted"}, {"label": "Retained", "value": "Retained"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const admissionsModule: ModuleConfig = {
  key: "admissions",
  title: "Admissions CRM",
  icon: "Ad",
  group: "Admissions",
  feature: "admissions",
  endpoint: "/admissions",
  titleField: "student_name",
  subtitleField: "inquiry_no",
  searchFields: ["student_name", "inquiry_no", "grade_applying", "academic_year"],
  listColumns: [{"key": "grade_applying", "label": "Grade Applying"}, {"key": "academic_year", "label": "Academic Year"}, {"key": "guardian_name", "label": "Guardian Name"}, {"key": "guardian_phone", "label": "Guardian Phone"}],
  formFields: [{"key": "inquiry_no", "label": "Inquiry No.", "type": "text", "required": true}, {"key": "student_name", "label": "Student Name", "type": "lookup", "lookup": {"endpoint": "/students", "valueField": "first_name", "searchFields": ["first_name", "last_name", "admission_no"], "subtitleFields": ["admission_no", "class_name"]}, "required": true}, {"key": "grade_applying", "label": "Grade Applying", "type": "lookup", "lookup": {"endpoint": "/classes", "valueField": "class_name", "searchFields": ["class_name"], "subtitleFields": ["section"]}, "required": true}, {"key": "academic_year", "label": "Academic Year", "type": "masterSelect", "masterCategory": "AcademicYear", "required": true}, {"key": "guardian_name", "label": "Guardian Name", "type": "text", "required": true}, {"key": "guardian_phone", "label": "Guardian Phone", "type": "phone", "required": true}, {"key": "guardian_email", "label": "Guardian Email", "type": "email"}, {"key": "source", "label": "Source", "type": "text"}, {"key": "stage", "label": "Stage", "type": "select", "options": [{"label": "Inquiry", "value": "Inquiry"}, {"label": "Application", "value": "Application"}, {"label": "Assessment", "value": "Assessment"}, {"label": "Offer", "value": "Offer"}, {"label": "Admitted", "value": "Admitted"}, {"label": "Rejected", "value": "Rejected"}, {"label": "Withdrawn", "value": "Withdrawn"}]}, {"key": "follow_up_date", "label": "Follow Up Date", "type": "date"}, {"key": "assigned_to", "label": "Assigned To", "type": "lookup", "lookup": {"endpoint": "/teachers", "valueField": "name", "searchFields": ["name", "employee_no"], "subtitleFields": ["department"]}}, {"key": "converted_student_id", "label": "Converted Student ID", "type": "number"}, {"key": "notes", "label": "Notes", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const admissionAssessmentsModule: ModuleConfig = {
  key: "admissionAssessments",
  title: "Admission Tests",
  icon: "At",
  group: "Admissions",
  feature: "admissions",
  featureFlag: "admission_assessments",
  roles: ["Admin", "Principal", "Teacher"],
  endpoint: "/admission-assessments",
  titleField: "assessment_type",
  subtitleField: "scheduled_time",
  searchFields: ["assessment_type", "scheduled_time", "mode", "panel_members"],
  listColumns: [{"key": "inquiry_id", "label": "Inquiry ID"}, {"key": "scheduled_date", "label": "Scheduled Date"}, {"key": "mode", "label": "Mode"}, {"key": "panel_members", "label": "Panel Members"}],
  formFields: [{"key": "inquiry_id", "label": "Inquiry ID", "type": "number", "required": true}, {"key": "assessment_type", "label": "Assessment Type", "type": "select", "options": [{"label": "Entrance Test", "value": "Entrance Test"}, {"label": "Student Interview", "value": "Student Interview"}, {"label": "Parent Interview", "value": "Parent Interview"}, {"label": "Portfolio Review", "value": "Portfolio Review"}, {"label": "Language Assessment", "value": "Language Assessment"}, {"label": "Counselor Meeting", "value": "Counselor Meeting"}], "required": true}, {"key": "scheduled_date", "label": "Scheduled Date", "type": "date", "required": true}, {"key": "scheduled_time", "label": "Scheduled Time", "type": "time"}, {"key": "mode", "label": "Mode", "type": "select", "options": [{"label": "On Campus", "value": "On Campus"}, {"label": "Online", "value": "Online"}, {"label": "Hybrid", "value": "Hybrid"}, {"label": "Phone", "value": "Phone"}]}, {"key": "panel_members", "label": "Panel Members", "type": "text"}, {"key": "location", "label": "Location", "type": "text"}, {"key": "status", "label": "Status", "type": "select", "options": [{"label": "Scheduled", "value": "Scheduled"}, {"label": "Completed", "value": "Completed"}, {"label": "Rescheduled", "value": "Rescheduled"}, {"label": "Cancelled", "value": "Cancelled"}, {"label": "No Show", "value": "No Show"}]}, {"key": "score", "label": "Score", "type": "number"}, {"key": "outcome", "label": "Outcome", "type": "text"}, {"key": "next_follow_up_date", "label": "Next Follow Up Date", "type": "date"}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const admissionStagesModule: ModuleConfig = {
  key: "admissionStages",
  title: "Admission Stages",
  icon: "As",
  group: "Admissions",
  feature: "admissions",
  endpoint: "/admission-workflow-stages",
  titleField: "name",
  searchFields: ["name"],
  listColumns: [{"key": "sort_order", "label": "Sort Order"}, {"key": "is_terminal", "label": "Is Terminal"}],
  formFields: [{"key": "name", "label": "Name", "type": "text", "required": true}, {"key": "sort_order", "label": "Sort Order", "type": "number"}, {"key": "is_terminal", "label": "Is Terminal", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const alumniWithdrawalsModule: ModuleConfig = {
  key: "alumniWithdrawals",
  title: "Alumni & Exit",
  icon: "Aw",
  group: "Admissions",
  feature: "alumni_withdrawals",
  roles: ["Admin", "Principal", "Teacher", "Accounts"],
  endpoint: "/alumni-withdrawals",
  titleField: "student_name",
  subtitleField: "record_no",
  searchFields: ["student_name", "record_no", "admission_no", "last_class"],
  listColumns: [{"key": "student_id", "label": "Student ID"}, {"key": "admission_no", "label": "Admission No."}, {"key": "last_class", "label": "Last Class"}, {"key": "record_type", "label": "Record Type"}],
  formFields: [{"key": "record_no", "label": "Record No.", "type": "text", "required": true}, {"key": "student_id", "label": "Student ID", "type": "reference", "reference": {"endpoint": "/students", "searchFields": ["first_name", "last_name", "admission_no"], "labelFields": ["first_name", "last_name"], "subtitleFields": ["admission_no", "class_name"]}}, {"key": "student_name", "label": "Student Name", "type": "lookup", "lookup": {"endpoint": "/students", "valueField": "first_name", "searchFields": ["first_name", "last_name", "admission_no"], "subtitleFields": ["admission_no", "class_name"]}, "required": true}, {"key": "admission_no", "label": "Admission No.", "type": "lookup", "lookup": {"endpoint": "/students", "valueField": "admission_no", "searchFields": ["admission_no", "first_name", "last_name"], "subtitleFields": ["first_name", "class_name"]}}, {"key": "last_class", "label": "Last Class", "type": "lookup", "lookup": {"endpoint": "/classes", "valueField": "class_name", "searchFields": ["class_name"], "subtitleFields": ["section"]}}, {"key": "record_type", "label": "Record Type", "type": "select", "options": [{"label": "Withdrawal", "value": "Withdrawal"}, {"label": "Transfer", "value": "Transfer"}, {"label": "Alumni", "value": "Alumni"}]}, {"key": "request_date", "label": "Request Date", "type": "date"}, {"key": "leaving_date", "label": "Leaving Date", "type": "date"}, {"key": "reason", "label": "Reason", "type": "text", "required": true}, {"key": "destination_school", "label": "Destination School", "type": "text"}, {"key": "destination_country", "label": "Destination Country", "type": "text"}, {"key": "certificate_status", "label": "Certificate Status", "type": "select", "options": [{"label": "Pending", "value": "Pending"}, {"label": "In Progress", "value": "In Progress"}, {"label": "Issued", "value": "Issued"}, {"label": "Rejected", "value": "Rejected"}, {"label": "Not Required", "value": "Not Required"}]}, {"key": "alumni_email", "label": "Alumni Email", "type": "email"}, {"key": "alumni_phone", "label": "Alumni Phone", "type": "phone"}, {"key": "current_status", "label": "Current Status", "type": "select", "options": [{"label": "Pending", "value": "Pending"}, {"label": "Approved", "value": "Approved"}, {"label": "Completed", "value": "Completed"}, {"label": "Rejected", "value": "Rejected"}, {"label": "Archived", "value": "Archived"}]}, {"key": "approved_by", "label": "Approved By", "type": "text"}, {"key": "approval_date", "label": "Approval Date", "type": "date"}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const feeStructuresModule: ModuleConfig = {
  key: "feeStructures",
  title: "Fee Structures",
  icon: "Fs",
  group: "Finance & Operations",
  feature: "fees",
  endpoint: "/fee-structures",
  titleField: "class_name",
  subtitleField: "academic_year",
  searchFields: ["class_name", "academic_year", "residential_type", "fee_type"],
  listColumns: [{"key": "residential_type", "label": "Residential Type"}, {"key": "fee_type", "label": "Fee Type"}, {"key": "amount", "label": "Amount"}, {"key": "due_date", "label": "Due Date"}],
  formFields: [{"key": "academic_year", "label": "Academic Year", "type": "masterSelect", "masterCategory": "AcademicYear", "required": true}, {"key": "class_name", "label": "Class Name", "type": "lookup", "lookup": {"endpoint": "/classes", "valueField": "class_name", "searchFields": ["class_name", "section"], "subtitleFields": ["section", "class_teacher"]}}, {"key": "residential_type", "label": "Residential Type", "type": "masterSelect", "masterCategory": "ResidentialType"}, {"key": "fee_type", "label": "Fee Type", "type": "masterSelect", "masterCategory": "FeeType", "required": true}, {"key": "amount", "label": "Amount", "type": "number", "required": true}, {"key": "due_date", "label": "Due Date", "type": "date"}, {"key": "remarks", "label": "Remarks", "type": "textarea"}, {"key": "auto_generate", "label": "Auto Generate", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "recurrence", "label": "Recurrence", "type": "select", "options": [{"label": "monthly", "value": "monthly"}, {"label": "quarterly", "value": "quarterly"}, {"label": "annually", "value": "annually"}, {"label": "once", "value": "once"}]}, {"key": "next_run_date", "label": "Next Run Date", "type": "date"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const accountingEntriesModule: ModuleConfig = {
  key: "accountingEntries",
  title: "Accounts",
  icon: "Ac",
  group: "Finance & Operations",
  feature: "accounting",
  endpoint: "/accounting/entries",
  titleField: "entry_type",
  subtitleField: "category",
  searchFields: ["entry_type", "category", "payment_mode", "reference_no"],
  listColumns: [{"key": "entry_date", "label": "Entry Date"}, {"key": "amount", "label": "Amount"}, {"key": "payment_mode", "label": "Payment Mode"}, {"key": "reference_no", "label": "Reference No."}],
  formFields: [{"key": "entry_date", "label": "Entry Date", "type": "date", "required": true}, {"key": "entry_type", "label": "Entry Type", "type": "select", "options": [{"label": "Income", "value": "Income"}, {"label": "Expense", "value": "Expense"}], "required": true}, {"key": "category", "label": "Category", "type": "text", "required": true}, {"key": "amount", "label": "Amount", "type": "number", "required": true}, {"key": "payment_mode", "label": "Payment Mode", "type": "select", "options": [{"label": "Cash", "value": "Cash"}, {"label": "Card", "value": "Card"}, {"label": "UPI", "value": "UPI"}, {"label": "Bank Transfer", "value": "Bank Transfer"}, {"label": "Cheque", "value": "Cheque"}]}, {"key": "reference_no", "label": "Reference No.", "type": "text"}, {"key": "description", "label": "Description", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const studentServicesModule: ModuleConfig = {
  key: "studentServices",
  title: "Student Services",
  icon: "Ss",
  group: "Student Wellbeing",
  feature: "student_services",
  endpoint: "/student-services",
  titleField: "requester_name",
  subtitleField: "ticket_no",
  searchFields: ["requester_name", "ticket_no", "requester_role", "contact_email"],
  listColumns: [{"key": "student_id", "label": "Student ID"}, {"key": "requester_role", "label": "Requester Role"}, {"key": "contact_phone", "label": "Contact Phone"}, {"key": "contact_email", "label": "Contact Email"}],
  formFields: [{"key": "ticket_no", "label": "Ticket No.", "type": "text", "required": true}, {"key": "student_id", "label": "Student ID", "type": "reference", "reference": {"endpoint": "/students", "searchFields": ["first_name", "last_name", "admission_no"], "labelFields": ["first_name", "last_name"], "subtitleFields": ["admission_no", "class_name"]}}, {"key": "requester_name", "label": "Requester Name", "type": "text", "required": true}, {"key": "requester_role", "label": "Requester Role", "type": "select", "options": [{"label": "Parent", "value": "Parent"}, {"label": "Student", "value": "Student"}, {"label": "Staff", "value": "Staff"}]}, {"key": "contact_phone", "label": "Contact Phone", "type": "phone"}, {"key": "contact_email", "label": "Contact Email", "type": "email"}, {"key": "category", "label": "Category", "type": "select", "options": [{"label": "General Request", "value": "General Request"}, {"label": "Counseling", "value": "Counseling"}, {"label": "Documents", "value": "Documents"}, {"label": "Transport", "value": "Transport"}, {"label": "Hostel", "value": "Hostel"}, {"label": "Fees", "value": "Fees"}, {"label": "Academics", "value": "Academics"}, {"label": "Facilities", "value": "Facilities"}, {"label": "Complaint", "value": "Complaint"}], "required": true}, {"key": "priority", "label": "Priority", "type": "select", "options": [{"label": "Low", "value": "Low"}, {"label": "Medium", "value": "Medium"}, {"label": "High", "value": "High"}, {"label": "Urgent", "value": "Urgent"}]}, {"key": "subject", "label": "Subject", "type": "lookup", "lookup": {"endpoint": "/subjects", "valueField": "subject_name", "searchFields": ["subject_name", "subject_code"], "subtitleFields": ["subject_code"]}, "required": true}, {"key": "description", "label": "Description", "type": "textarea", "required": true}, {"key": "assigned_to", "label": "Assigned To", "type": "lookup", "lookup": {"endpoint": "/teachers", "valueField": "name", "searchFields": ["name", "employee_no"], "subtitleFields": ["department"]}}, {"key": "due_date", "label": "Due Date", "type": "date"}, {"key": "status", "label": "Status", "type": "select", "options": [{"label": "Open", "value": "Open"}, {"label": "In Progress", "value": "In Progress"}, {"label": "Waiting", "value": "Waiting"}, {"label": "Resolved", "value": "Resolved"}, {"label": "Closed", "value": "Closed"}]}, {"key": "resolution", "label": "Resolution", "type": "text"}, {"key": "closed_date", "label": "Closed Date", "type": "date"}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const counselingModule: ModuleConfig = {
  key: "counseling",
  title: "Counseling",
  icon: "Co",
  group: "Student Wellbeing",
  feature: "counseling",
  endpoint: "/counseling",
  titleField: "case_no",
  subtitleField: "concern_type",
  searchFields: ["case_no", "concern_type", "risk_level", "reported_by"],
  listColumns: [{"key": "student_id", "label": "Student ID"}, {"key": "risk_level", "label": "Risk Level"}, {"key": "reported_by", "label": "Reported By"}, {"key": "counselor", "label": "Counselor"}],
  formFields: [{"key": "case_no", "label": "Case No.", "type": "text", "required": true}, {"key": "student_id", "label": "Student ID", "type": "reference", "reference": {"endpoint": "/students", "searchFields": ["first_name", "last_name", "admission_no"], "labelFields": ["first_name", "last_name"], "subtitleFields": ["admission_no", "class_name"]}, "required": true}, {"key": "concern_type", "label": "Concern Type", "type": "text", "required": true}, {"key": "risk_level", "label": "Risk Level", "type": "select", "options": [{"label": "Low", "value": "Low"}, {"label": "Medium", "value": "Medium"}, {"label": "High", "value": "High"}, {"label": "Critical", "value": "Critical"}]}, {"key": "reported_by", "label": "Reported By", "type": "text"}, {"key": "counselor", "label": "Counselor", "type": "lookup", "lookup": {"endpoint": "/teachers", "valueField": "name", "searchFields": ["name", "employee_no"], "subtitleFields": ["department"]}}, {"key": "session_date", "label": "Session Date", "type": "date"}, {"key": "next_follow_up_date", "label": "Next Follow Up Date", "type": "date"}, {"key": "guardian_contacted", "label": "Guardian Contacted", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "action_plan", "label": "Action Plan", "type": "text"}, {"key": "confidentiality_level", "label": "Confidentiality Level", "type": "select", "options": [{"label": "Standard", "value": "Standard"}, {"label": "Restricted", "value": "Restricted"}, {"label": "Sensitive", "value": "Sensitive"}]}, {"key": "status", "label": "Status", "type": "select", "options": [{"label": "Open", "value": "Open"}, {"label": "In Progress", "value": "In Progress"}, {"label": "Monitoring", "value": "Monitoring"}, {"label": "Closed", "value": "Closed"}, {"label": "Escalated", "value": "Escalated"}]}, {"key": "outcome", "label": "Outcome", "type": "text"}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const enrichmentModule: ModuleConfig = {
  key: "enrichment",
  title: "Enrichment",
  icon: "Er",
  group: "Student Wellbeing",
  feature: "enrichment",
  endpoint: "/enrichment",
  titleField: "activity_name",
  subtitleField: "activity_code",
  searchFields: ["activity_name", "activity_code", "activity_type", "category"],
  listColumns: [{"key": "activity_type", "label": "Activity Type"}, {"key": "category", "label": "Category"}, {"key": "coordinator", "label": "Coordinator"}, {"key": "start_date", "label": "Start Date"}],
  formFields: [{"key": "activity_code", "label": "Activity Code", "type": "text", "required": true}, {"key": "activity_name", "label": "Activity Name", "type": "text", "required": true}, {"key": "activity_type", "label": "Activity Type", "type": "select", "options": [{"label": "Club", "value": "Club"}, {"label": "Sport", "value": "Sport"}, {"label": "Competition", "value": "Competition"}, {"label": "Trip", "value": "Trip"}, {"label": "Service Learning", "value": "Service Learning"}, {"label": "CAS", "value": "CAS"}, {"label": "Workshop", "value": "Workshop"}, {"label": "Event", "value": "Event"}], "required": true}, {"key": "category", "label": "Category", "type": "text"}, {"key": "coordinator", "label": "Coordinator", "type": "lookup", "lookup": {"endpoint": "/teachers", "valueField": "name", "searchFields": ["name", "employee_no"], "subtitleFields": ["department"]}}, {"key": "start_date", "label": "Start Date", "type": "date"}, {"key": "end_date", "label": "End Date", "type": "date"}, {"key": "venue", "label": "Venue", "type": "text"}, {"key": "eligible_classes", "label": "Eligible Classes", "type": "lookup", "lookup": {"endpoint": "/classes", "valueField": "class_name", "searchFields": ["class_name"], "subtitleFields": ["section"]}}, {"key": "capacity", "label": "Capacity", "type": "number"}, {"key": "enrolled_count", "label": "Enrolled Count", "type": "number"}, {"key": "fee_amount", "label": "Fee Amount", "type": "number"}, {"key": "status", "label": "Status", "type": "select", "options": [{"label": "Planned", "value": "Planned"}, {"label": "Open", "value": "Open"}, {"label": "Full", "value": "Full"}, {"label": "Completed", "value": "Completed"}, {"label": "Cancelled", "value": "Cancelled"}]}, {"key": "description", "label": "Description", "type": "textarea"}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const complianceModule: ModuleConfig = {
  key: "compliance",
  title: "Compliance",
  icon: "Cm",
  group: "Student Wellbeing",
  feature: "compliance",
  endpoint: "/compliance",
  titleField: "task_code",
  subtitleField: "accreditation_body",
  searchFields: ["task_code", "accreditation_body", "standard_area", "requirement"],
  listColumns: [{"key": "standard_area", "label": "Standard Area"}, {"key": "requirement", "label": "Requirement"}, {"key": "evidence_link", "label": "Evidence Link"}, {"key": "owner", "label": "Owner"}],
  formFields: [{"key": "task_code", "label": "Task Code", "type": "text", "required": true}, {"key": "accreditation_body", "label": "Accreditation Body", "type": "text", "required": true}, {"key": "standard_area", "label": "Standard Area", "type": "text", "required": true}, {"key": "requirement", "label": "Requirement", "type": "text", "required": true}, {"key": "evidence_link", "label": "Evidence Link", "type": "text"}, {"key": "owner", "label": "Owner", "type": "lookup", "lookup": {"endpoint": "/teachers", "valueField": "name", "searchFields": ["name", "employee_no"], "subtitleFields": ["department"]}}, {"key": "due_date", "label": "Due Date", "type": "date"}, {"key": "review_date", "label": "Review Date", "type": "date"}, {"key": "risk_level", "label": "Risk Level", "type": "select", "options": [{"label": "Low", "value": "Low"}, {"label": "Medium", "value": "Medium"}, {"label": "High", "value": "High"}, {"label": "Critical", "value": "Critical"}]}, {"key": "status", "label": "Status", "type": "select", "options": [{"label": "Open", "value": "Open"}, {"label": "In Progress", "value": "In Progress"}, {"label": "Evidence Ready", "value": "Evidence Ready"}, {"label": "Reviewed", "value": "Reviewed"}, {"label": "Completed", "value": "Completed"}, {"label": "Deferred", "value": "Deferred"}]}, {"key": "finding", "label": "Finding", "type": "text"}, {"key": "action_plan", "label": "Action Plan", "type": "text"}, {"key": "completed_date", "label": "Completed Date", "type": "date"}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const internationalDocumentsModule: ModuleConfig = {
  key: "internationalDocuments",
  title: "Intl. Documents",
  icon: "Id",
  group: "Admissions",
  feature: "international_documents",
  endpoint: "/international-documents",
  titleField: "document_type",
  subtitleField: "document_no",
  searchFields: ["document_type", "document_no", "issuing_country", "status"],
  listColumns: [{"key": "student_id", "label": "Student ID"}, {"key": "issue_date", "label": "Issue Date"}, {"key": "expiry_date", "label": "Expiry Date"}, {"key": "issuing_country", "label": "Issuing Country"}],
  formFields: [{"key": "student_id", "label": "Student ID", "type": "reference", "reference": {"endpoint": "/students", "searchFields": ["first_name", "last_name", "admission_no"], "labelFields": ["first_name", "last_name"], "subtitleFields": ["admission_no", "class_name"]}, "required": true}, {"key": "document_type", "label": "Document Type", "type": "select", "options": [{"label": "Passport", "value": "Passport"}, {"label": "Visa", "value": "Visa"}, {"label": "Residence Permit", "value": "Residence Permit"}, {"label": "Birth Certificate", "value": "Birth Certificate"}, {"label": "Transfer Certificate", "value": "Transfer Certificate"}, {"label": "Immunisation Record", "value": "Immunisation Record"}, {"label": "Insurance", "value": "Insurance"}, {"label": "Other", "value": "Other"}], "required": true}, {"key": "document_no", "label": "Document No.", "type": "text"}, {"key": "issue_date", "label": "Issue Date", "type": "date"}, {"key": "expiry_date", "label": "Expiry Date", "type": "date"}, {"key": "issuing_country", "label": "Issuing Country", "type": "text"}, {"key": "status", "label": "Status", "type": "select", "options": [{"label": "Pending", "value": "Pending"}, {"label": "Submitted", "value": "Submitted"}, {"label": "Verified", "value": "Verified"}, {"label": "Rejected", "value": "Rejected"}, {"label": "Expired", "value": "Expired"}]}, {"key": "file_url", "label": "File URL", "type": "photo"}, {"key": "verified_by", "label": "Verified By", "type": "lookup", "lookup": {"endpoint": "/teachers", "valueField": "name", "searchFields": ["name", "employee_no"], "subtitleFields": ["department"]}}, {"key": "verified_date", "label": "Verified Date", "type": "date"}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const healthVisitsModule: ModuleConfig = {
  key: "healthVisits",
  title: "Infirmary Visits",
  icon: "Hi",
  group: "Student Wellbeing",
  feature: "health_infirmary",
  endpoint: "/health-infirmary/visits",
  titleField: "visit_time",
  subtitleField: "symptoms",
  searchFields: ["visit_time", "symptoms", "diagnosis", "treatment"],
  listColumns: [{"key": "student_id", "label": "Student ID"}, {"key": "visit_date", "label": "Visit Date"}, {"key": "diagnosis", "label": "Diagnosis"}, {"key": "treatment", "label": "Treatment"}],
  formFields: [{"key": "student_id", "label": "Student ID", "type": "reference", "reference": {"endpoint": "/students", "searchFields": ["first_name", "last_name", "admission_no"], "labelFields": ["first_name", "last_name"], "subtitleFields": ["admission_no", "class_name"]}, "required": true}, {"key": "visit_date", "label": "Visit Date", "type": "date", "required": true}, {"key": "visit_time", "label": "Visit Time", "type": "time"}, {"key": "symptoms", "label": "Symptoms", "type": "text", "required": true}, {"key": "diagnosis", "label": "Diagnosis", "type": "text"}, {"key": "treatment", "label": "Treatment", "type": "text"}, {"key": "medicine_given", "label": "Medicine Given", "type": "text"}, {"key": "attended_by", "label": "Attended By", "type": "lookup", "lookup": {"endpoint": "/teachers", "valueField": "name", "searchFields": ["name", "employee_no"], "subtitleFields": ["department"]}}, {"key": "referred_to_hospital", "label": "Referred To Hospital", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "follow_up_date", "label": "Follow Up Date", "type": "date"}, {"key": "status", "label": "Status", "type": "select", "options": [{"label": "Open", "value": "Open"}, {"label": "Referred", "value": "Referred"}, {"label": "Closed", "value": "Closed"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const libraryBooksModule: ModuleConfig = {
  key: "libraryBooks",
  title: "Library Books",
  icon: "Lb",
  group: "Finance & Operations",
  feature: "library",
  endpoint: "/library/books",
  titleField: "title",
  subtitleField: "accession_no",
  searchFields: ["title", "accession_no", "author", "category"],
  listColumns: [{"key": "author", "label": "Author"}, {"key": "category", "label": "Category"}, {"key": "publisher", "label": "Publisher"}, {"key": "isbn", "label": "ISBN"}],
  formFields: [{"key": "accession_no", "label": "Accession No.", "type": "text", "required": true}, {"key": "title", "label": "Title", "type": "text", "required": true}, {"key": "author", "label": "Author", "type": "text"}, {"key": "category", "label": "Category", "type": "masterSelect", "masterCategory": "LibraryCategory"}, {"key": "publisher", "label": "Publisher", "type": "text"}, {"key": "isbn", "label": "ISBN", "type": "text"}, {"key": "total_copies", "label": "Total Copies", "type": "number"}, {"key": "available_copies", "label": "Available Copies", "type": "number"}, {"key": "shelf_no", "label": "Shelf No.", "type": "text"}, {"key": "status", "label": "Status", "type": "select", "options": [{"label": "Available", "value": "Available"}, {"label": "Unavailable", "value": "Unavailable"}, {"label": "Damaged", "value": "Damaged"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const libraryIssuesModule: ModuleConfig = {
  key: "libraryIssues",
  title: "Book Issues",
  icon: "Li",
  group: "Finance & Operations",
  feature: "library",
  endpoint: "/library/issues",
  titleField: "status",
  searchFields: ["status"],
  listColumns: [{"key": "book_id", "label": "Book ID"}, {"key": "borrower_type", "label": "Borrower Type"}, {"key": "student_id", "label": "Student ID"}, {"key": "staff_id", "label": "Staff ID"}, {"key": "issue_date", "label": "Issue Date"}, {"key": "due_date", "label": "Due Date"}, {"key": "renewal_count", "label": "Renewals"}],
  formFields: [{"key": "book_id", "label": "Book ID", "type": "reference", "reference": {"endpoint": "/library/books", "searchFields": ["title", "author", "accession_no"], "labelFields": ["title"], "subtitleFields": ["author", "accession_no"]}, "required": true}, {"key": "borrower_type", "label": "Borrower Type", "type": "select", "options": [{"label": "Student", "value": "Student"}, {"label": "Staff", "value": "Staff"}]}, {"key": "student_id", "label": "Student ID", "type": "reference", "reference": {"endpoint": "/students", "searchFields": ["first_name", "last_name", "admission_no"], "labelFields": ["first_name", "last_name"], "subtitleFields": ["admission_no", "class_name"]}}, {"key": "staff_id", "label": "Staff ID", "type": "reference", "reference": {"endpoint": "/teachers", "searchFields": ["name", "employee_no"], "labelFields": ["name"], "subtitleFields": ["employee_no", "department"]}}, {"key": "issue_date", "label": "Issue Date", "type": "date", "required": true}, {"key": "due_date", "label": "Due Date", "type": "date"}, {"key": "return_date", "label": "Return Date", "type": "date"}, {"key": "status", "label": "Status", "type": "select", "options": [{"label": "Issued", "value": "Issued"}, {"label": "Returned", "value": "Returned"}, {"label": "Lost", "value": "Lost"}, {"label": "Damaged", "value": "Damaged"}]}, {"key": "fine_amount", "label": "Fine Amount", "type": "number"}, {"key": "fine_paid", "label": "Fine Paid", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const libraryReservationsModule: ModuleConfig = {
  key: "libraryReservations",
  title: "Library Reservations",
  icon: "Lr",
  group: "Finance & Operations",
  feature: "library",
  endpoint: "/library/reservations",
  titleField: "status",
  subtitleField: "queue_position",
  searchFields: ["status", "borrower_type"],
  listColumns: [{"key": "book_id", "label": "Book ID"}, {"key": "borrower_type", "label": "Borrower Type"}, {"key": "queue_position", "label": "Queue #"}, {"key": "status", "label": "Status"}],
  formFields: [{"key": "book_id", "label": "Book ID", "type": "reference", "reference": {"endpoint": "/library/books", "searchFields": ["title", "author", "accession_no"], "labelFields": ["title"], "subtitleFields": ["author", "accession_no"]}, "required": true}, {"key": "borrower_type", "label": "Borrower Type", "type": "select", "options": [{"label": "Student", "value": "Student"}, {"label": "Staff", "value": "Staff"}]}, {"key": "student_id", "label": "Student ID", "type": "reference", "reference": {"endpoint": "/students", "searchFields": ["first_name", "last_name", "admission_no"], "labelFields": ["first_name", "last_name"], "subtitleFields": ["admission_no", "class_name"]}}, {"key": "staff_id", "label": "Staff ID", "type": "reference", "reference": {"endpoint": "/teachers", "searchFields": ["name", "employee_no"], "labelFields": ["name"], "subtitleFields": ["employee_no", "department"]}}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: false,
  allowDelete: true,
};

export const hostelBlocksModule: ModuleConfig = {
  key: "hostelBlocks",
  title: "Hostel Blocks",
  icon: "Hb",
  group: "Finance & Operations",
  feature: "hostel",
  endpoint: "/hostel/blocks",
  titleField: "block_name",
  subtitleField: "hostel_type",
  searchFields: ["block_name", "hostel_type", "warden_name"],
  listColumns: [{"key": "warden_name", "label": "Warden Name"}, {"key": "warden_phone", "label": "Warden Phone"}, {"key": "is_active", "label": "Is Active"}, {"key": "remarks", "label": "Remarks"}],
  formFields: [{"key": "block_name", "label": "Block Name", "type": "lookup", "lookup": {"endpoint": "/hostel/blocks", "valueField": "block_name", "searchFields": ["block_name"], "subtitleFields": ["hostel_type"]}, "required": true}, {"key": "hostel_type", "label": "Hostel Type", "type": "select", "options": [{"label": "Boys", "value": "Boys"}, {"label": "Girls", "value": "Girls"}, {"label": "Mixed", "value": "Mixed"}]}, {"key": "warden_name", "label": "Warden Name", "type": "lookup", "lookup": {"endpoint": "/teachers", "valueField": "name", "searchFields": ["name", "employee_no"], "subtitleFields": ["department"]}}, {"key": "warden_phone", "label": "Warden Phone", "type": "phone"}, {"key": "is_active", "label": "Is Active", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const hostelRoomsModule: ModuleConfig = {
  key: "hostelRooms",
  title: "Hostel Rooms",
  icon: "Hr",
  group: "Finance & Operations",
  feature: "hostel",
  endpoint: "/hostel/rooms",
  titleField: "room_no",
  subtitleField: "floor",
  searchFields: ["room_no", "floor"],
  listColumns: [{"key": "block_id", "label": "Block ID"}, {"key": "capacity", "label": "Capacity"}, {"key": "is_active", "label": "Is Active"}, {"key": "remarks", "label": "Remarks"}],
  formFields: [{"key": "block_id", "label": "Block ID", "type": "reference", "reference": {"endpoint": "/hostel/blocks", "searchFields": ["block_name"], "labelFields": ["block_name"], "subtitleFields": ["hostel_type"]}, "required": true}, {"key": "room_no", "label": "Room No.", "type": "text", "required": true}, {"key": "floor", "label": "Floor", "type": "text"}, {"key": "capacity", "label": "Capacity", "type": "number"}, {"key": "is_active", "label": "Is Active", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const hostelAllocationsModule: ModuleConfig = {
  key: "hostelAllocations",
  title: "Room Allocations",
  icon: "Ha",
  group: "Finance & Operations",
  feature: "hostel",
  endpoint: "/hostel/allocations",
  titleField: "bed_no",
  subtitleField: "status",
  searchFields: ["bed_no", "status"],
  listColumns: [{"key": "student_id", "label": "Student ID"}, {"key": "room_id", "label": "Room ID"}, {"key": "start_date", "label": "Start Date"}, {"key": "end_date", "label": "End Date"}],
  formFields: [{"key": "student_id", "label": "Student ID", "type": "reference", "reference": {"endpoint": "/students", "searchFields": ["first_name", "last_name", "admission_no"], "labelFields": ["first_name", "last_name"], "subtitleFields": ["admission_no", "class_name"]}, "required": true}, {"key": "room_id", "label": "Room ID", "type": "reference", "reference": {"endpoint": "/hostel/rooms", "searchFields": ["room_no"], "labelFields": ["room_no"], "subtitleFields": ["capacity"]}, "required": true}, {"key": "bed_no", "label": "Bed No.", "type": "text", "required": true}, {"key": "start_date", "label": "Start Date", "type": "date"}, {"key": "end_date", "label": "End Date", "type": "date"}, {"key": "status", "label": "Status", "type": "select", "options": [{"label": "Active", "value": "Active"}, {"label": "Completed", "value": "Completed"}, {"label": "Cancelled", "value": "Cancelled"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const transportRoutesModule: ModuleConfig = {
  key: "transportRoutes",
  title: "Routes",
  icon: "Tr",
  group: "Finance & Operations",
  feature: "transport",
  endpoint: "/transport/routes",
  titleField: "route_name",
  subtitleField: "start_point",
  searchFields: ["route_name", "start_point", "end_point"],
  listColumns: [{"key": "end_point", "label": "End Point"}, {"key": "monthly_fee", "label": "Monthly Fee"}, {"key": "is_active", "label": "Is Active"}, {"key": "remarks", "label": "Remarks"}],
  formFields: [{"key": "route_name", "label": "Route Name", "type": "lookup", "lookup": {"endpoint": "/transport/routes", "valueField": "route_name", "searchFields": ["route_name"], "subtitleFields": ["start_point", "end_point"]}, "required": true}, {"key": "start_point", "label": "Start Point", "type": "text"}, {"key": "end_point", "label": "End Point", "type": "text"}, {"key": "monthly_fee", "label": "Monthly Fee", "type": "number"}, {"key": "is_active", "label": "Is Active", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const transportStopsModule: ModuleConfig = {
  key: "transportStops",
  title: "Stops",
  icon: "Ts",
  group: "Finance & Operations",
  feature: "transport",
  endpoint: "/transport/stops",
  titleField: "stop_name",
  subtitleField: "pickup_time",
  searchFields: ["stop_name", "pickup_time", "drop_time"],
  listColumns: [{"key": "route_id", "label": "Route ID"}, {"key": "drop_time", "label": "Drop Time"}, {"key": "sort_order", "label": "Sort Order"}, {"key": "is_active", "label": "Is Active"}],
  formFields: [{"key": "route_id", "label": "Route ID", "type": "reference", "reference": {"endpoint": "/transport/routes", "searchFields": ["route_name"], "labelFields": ["route_name"], "subtitleFields": ["start_point", "end_point"]}, "required": true}, {"key": "stop_name", "label": "Stop Name", "type": "text", "required": true}, {"key": "pickup_time", "label": "Pickup Time", "type": "time"}, {"key": "drop_time", "label": "Drop Time", "type": "time"}, {"key": "sort_order", "label": "Sort Order", "type": "number"}, {"key": "is_active", "label": "Is Active", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const transportVehiclesModule: ModuleConfig = {
  key: "transportVehicles",
  title: "Vehicles",
  icon: "Tv",
  group: "Finance & Operations",
  feature: "transport",
  endpoint: "/transport/vehicles",
  titleField: "driver_name",
  subtitleField: "vehicle_no",
  searchFields: ["driver_name", "vehicle_no", "vehicle_type", "attendant_name"],
  listColumns: [{"key": "route_id", "label": "Route ID"}, {"key": "vehicle_type", "label": "Vehicle Type"}, {"key": "capacity", "label": "Capacity"}, {"key": "driver_phone", "label": "Driver Phone"}],
  formFields: [{"key": "vehicle_no", "label": "Vehicle No.", "type": "lookup", "lookup": {"endpoint": "/transport/vehicles", "valueField": "vehicle_no", "searchFields": ["vehicle_no", "driver_name"], "subtitleFields": ["driver_name"]}, "required": true}, {"key": "route_id", "label": "Route ID", "type": "reference", "reference": {"endpoint": "/transport/routes", "searchFields": ["route_name"], "labelFields": ["route_name"], "subtitleFields": ["start_point", "end_point"]}}, {"key": "vehicle_type", "label": "Vehicle Type", "type": "select", "options": [{"label": "Bus", "value": "Bus"}, {"label": "Van", "value": "Van"}, {"label": "Car", "value": "Car"}, {"label": "Tempo Traveller", "value": "Tempo Traveller"}]}, {"key": "capacity", "label": "Capacity", "type": "number"}, {"key": "driver_name", "label": "Driver Name", "type": "text"}, {"key": "driver_phone", "label": "Driver Phone", "type": "phone"}, {"key": "attendant_name", "label": "Attendant Name", "type": "text"}, {"key": "is_active", "label": "Is Active", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const transportAssignmentsModule: ModuleConfig = {
  key: "transportAssignments",
  title: "Transport Assignments",
  icon: "Ta",
  group: "Finance & Operations",
  feature: "transport",
  endpoint: "/transport/assignments",
  titleField: "status",
  searchFields: ["status"],
  listColumns: [{"key": "student_id", "label": "Student ID"}, {"key": "route_id", "label": "Route ID"}, {"key": "vehicle_id", "label": "Vehicle ID"}, {"key": "stop_id", "label": "Stop ID"}],
  formFields: [{"key": "student_id", "label": "Student ID", "type": "reference", "reference": {"endpoint": "/students", "searchFields": ["first_name", "last_name", "admission_no"], "labelFields": ["first_name", "last_name"], "subtitleFields": ["admission_no", "class_name"]}, "required": true}, {"key": "route_id", "label": "Route ID", "type": "reference", "reference": {"endpoint": "/transport/routes", "searchFields": ["route_name"], "labelFields": ["route_name"], "subtitleFields": ["start_point", "end_point"]}, "required": true}, {"key": "vehicle_id", "label": "Vehicle ID", "type": "reference", "reference": {"endpoint": "/transport/vehicles", "searchFields": ["vehicle_no", "driver_name"], "labelFields": ["vehicle_no"], "subtitleFields": ["driver_name"]}}, {"key": "stop_id", "label": "Stop ID", "type": "reference", "reference": {"endpoint": "/transport/stops", "searchFields": ["stop_name"], "labelFields": ["stop_name"], "subtitleFields": ["pickup_time"]}}, {"key": "start_date", "label": "Start Date", "type": "date"}, {"key": "end_date", "label": "End Date", "type": "date"}, {"key": "status", "label": "Status", "type": "select", "options": [{"label": "Active", "value": "Active"}, {"label": "Completed", "value": "Completed"}, {"label": "Cancelled", "value": "Cancelled"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const inventoryItemsModule: ModuleConfig = {
  key: "inventoryItems",
  title: "Inventory",
  icon: "In",
  group: "Finance & Operations",
  feature: "inventory",
  roles: ["Admin", "Principal", "Accounts", "Teacher"],
  endpoint: "/inventory/items",
  titleField: "item_name",
  subtitleField: "item_code",
  searchFields: ["item_name", "item_code", "barcode", "category", "unit"],
  listColumns: [{"key": "category", "label": "Category"}, {"key": "unit", "label": "Unit"}, {"key": "quantity_available", "label": "Quantity Available"}, {"key": "reorder_level", "label": "Reorder Level"}],
  formFields: [{"key": "item_name", "label": "Item Name", "type": "text", "required": true}, {"key": "item_code", "label": "Item Code", "type": "text"}, {"key": "barcode", "label": "Barcode", "type": "text"}, {"key": "category", "label": "Category", "type": "masterSelect", "masterCategory": "InventoryCategory"}, {"key": "unit", "label": "Unit", "type": "masterSelect", "masterCategory": "InventoryUnit"}, {"key": "quantity_available", "label": "Quantity Available", "type": "number"}, {"key": "reorder_level", "label": "Reorder Level", "type": "number"}, {"key": "unit_price", "label": "Unit Price", "type": "number"}, {"key": "location", "label": "Location", "type": "text"}, {"key": "status", "label": "Status", "type": "select", "options": [{"label": "Active", "value": "Active"}, {"label": "Inactive", "value": "Inactive"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const inventoryKitsModule: ModuleConfig = {
  key: "inventoryKits",
  title: "Inventory Kits",
  icon: "Ik",
  group: "Finance & Operations",
  feature: "inventory",
  roles: ["Admin", "Principal", "Accounts", "Teacher"],
  endpoint: "/inventory/kits",
  titleField: "name",
  subtitleField: "applies_to",
  searchFields: ["name", "applies_to"],
  listColumns: [{"key": "applies_to", "label": "Applies To"}, {"key": "is_active", "label": "Is Active"}, {"key": "remarks", "label": "Remarks"}],
  formFields: [{"key": "name", "label": "Name", "type": "text", "required": true}, {"key": "applies_to", "label": "Applies To", "type": "select", "options": [{"label": "Student", "value": "Student"}, {"label": "Staff", "value": "Staff"}], "required": true}, {"key": "is_active", "label": "Is Active", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const inventoryTransactionsModule: ModuleConfig = {
  key: "inventoryTransactions",
  title: "Stock Movements",
  icon: "Sm",
  group: "Finance & Operations",
  feature: "inventory",
  roles: ["Admin", "Principal", "Accounts", "Teacher"],
  endpoint: "/inventory/transactions",
  titleField: "transaction_type",
  subtitleField: "transaction_date",
  searchFields: ["transaction_type", "item_name", "item_code", "student_name", "teacher_name"],
  listColumns: [{"key": "item_name", "label": "Item"}, {"key": "quantity", "label": "Quantity"}, {"key": "transaction_date", "label": "Date"}, {"key": "amount", "label": "Amount"}],
  formFields: [{"key": "item_id", "label": "Item", "type": "reference", "reference": {"endpoint": "/inventory/items", "searchFields": ["item_name", "item_code", "barcode"], "labelFields": ["item_name"], "subtitleFields": ["item_code", "quantity_available"]}, "required": true}, {"key": "transaction_date", "label": "Transaction Date", "type": "date", "required": true}, {"key": "transaction_type", "label": "Transaction Type", "type": "select", "options": [{"label": "Stock In", "value": "Stock In"}, {"label": "Stock Out", "value": "Stock Out"}, {"label": "Issue", "value": "Issue"}, {"label": "Purchase", "value": "Purchase"}, {"label": "Return", "value": "Return"}, {"label": "Adjustment", "value": "Adjustment"}], "required": true}, {"key": "quantity", "label": "Quantity", "type": "number", "required": true}, {"key": "issued_to_student_id", "label": "Student", "type": "reference", "reference": {"endpoint": "/students", "searchFields": ["first_name", "last_name", "admission_no"], "labelFields": ["first_name", "last_name"], "subtitleFields": ["admission_no", "class_name"]}}, {"key": "issued_to_teacher_id", "label": "Staff Member", "type": "reference", "reference": {"endpoint": "/teachers", "searchFields": ["name", "employee_no"], "labelFields": ["name"], "subtitleFields": ["employee_no", "department"]}}, {"key": "issued_to_staff", "label": "Other Staff (not in directory)", "type": "text"}, {"key": "unit_cost", "label": "Unit Cost", "type": "number"}, {"key": "unit_price", "label": "Unit Price (Purchase)", "type": "number"}, {"key": "payment_status", "label": "Payment Status", "type": "select", "options": [{"label": "Paid", "value": "Paid"}, {"label": "Unpaid", "value": "Unpaid"}]}, {"key": "reference_no", "label": "Reference No.", "type": "text"}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: false,
  allowDelete: true,
};

export const messMenusModule: ModuleConfig = {
  key: "messMenus",
  title: "Mess Menus",
  icon: "Mm",
  group: "Finance & Operations",
  feature: "mess_management",
  endpoint: "/mess/menus",
  titleField: "meal_type",
  subtitleField: "menu_items",
  searchFields: ["meal_type", "menu_items", "nutrition_notes", "allergen_notes"],
  listColumns: [{"key": "menu_date", "label": "Menu Date"}, {"key": "nutrition_notes", "label": "Nutrition Notes"}, {"key": "allergen_notes", "label": "Allergen Notes"}, {"key": "is_published", "label": "Is Published"}],
  formFields: [{"key": "menu_date", "label": "Menu Date", "type": "date", "required": true}, {"key": "meal_type", "label": "Meal Type", "type": "select", "options": [{"label": "Breakfast", "value": "Breakfast"}, {"label": "Lunch", "value": "Lunch"}, {"label": "Snacks", "value": "Snacks"}, {"label": "Dinner", "value": "Dinner"}], "required": true}, {"key": "menu_items", "label": "Menu Items", "type": "text", "required": true}, {"key": "nutrition_notes", "label": "Nutrition Notes", "type": "text"}, {"key": "allergen_notes", "label": "Allergen Notes", "type": "text"}, {"key": "is_published", "label": "Is Published", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const messAttendanceModule: ModuleConfig = {
  key: "messAttendance",
  title: "Mess Attendance",
  icon: "Ma",
  group: "Finance & Operations",
  feature: "mess_management",
  endpoint: "/mess/attendance",
  titleField: "meal_type",
  subtitleField: "status",
  searchFields: ["meal_type", "status"],
  listColumns: [{"key": "student_id", "label": "Student ID"}, {"key": "meal_date", "label": "Meal Date"}, {"key": "remarks", "label": "Remarks"}],
  formFields: [{"key": "student_id", "label": "Student ID", "type": "reference", "reference": {"endpoint": "/students", "searchFields": ["first_name", "last_name", "admission_no"], "labelFields": ["first_name", "last_name"], "subtitleFields": ["admission_no", "class_name"]}, "required": true}, {"key": "meal_date", "label": "Meal Date", "type": "date", "required": true}, {"key": "meal_type", "label": "Meal Type", "type": "select", "options": [{"label": "Breakfast", "value": "Breakfast"}, {"label": "Lunch", "value": "Lunch"}, {"label": "Snacks", "value": "Snacks"}, {"label": "Dinner", "value": "Dinner"}], "required": true}, {"key": "status", "label": "Status", "type": "select", "options": [{"label": "Present", "value": "Present"}, {"label": "Absent", "value": "Absent"}, {"label": "Excused", "value": "Excused"}, {"label": "Packed Meal", "value": "Packed Meal"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const masterDataModule: ModuleConfig = {
  key: "masterData",
  title: "Master Data",
  icon: "Md",
  group: "Reports & Administration",
  feature: "master_data",
  endpoint: "/master-data",
  // /master-data/{id} is the by-category route, which answers 400 for a
  // numeric id rather than 404 — so the row is found in the list instead.
  hasDetailRoute: false,
  titleField: "category",
  subtitleField: "value",
  searchFields: ["category", "value"],
  listColumns: [{"key": "is_active", "label": "Is Active"}, {"key": "sort_order", "label": "Sort Order"}],
  formFields: [{"key": "category", "label": "Category", "type": "select", "options": [{"label": "Class", "value": "Class"}, {"label": "Exam", "value": "Exam"}, {"label": "Department", "value": "Department"}, {"label": "Subject", "value": "Subject"}, {"label": "House", "value": "House"}, {"label": "Section", "value": "Section"}, {"label": "FeeType", "value": "FeeType"}, {"label": "AttendanceStatus", "value": "AttendanceStatus"}, {"label": "ExamType", "value": "ExamType"}, {"label": "EmploymentType", "value": "EmploymentType"}, {"label": "Gender", "value": "Gender"}, {"label": "BloodGroup", "value": "BloodGroup"}, {"label": "Nationality", "value": "Nationality"}, {"label": "TransportRoute", "value": "TransportRoute"}, {"label": "LibraryCategory", "value": "LibraryCategory"}, {"label": "InventoryCategory", "value": "InventoryCategory"}, {"label": "InventoryUnit", "value": "InventoryUnit"}, {"label": "SalaryGrade", "value": "SalaryGrade"}, {"label": "StudentStatus", "value": "StudentStatus"}, {"label": "AcademicYear", "value": "AcademicYear"}, {"label": "ResidentialType", "value": "ResidentialType"}], "required": true}, {"key": "value", "label": "Value", "type": "text", "required": true}, {"key": "is_active", "label": "Is Active", "type": "select", "options": [{"label": "Yes", "value": "true"}, {"label": "No", "value": "false"}]}, {"key": "sort_order", "label": "Sort Order", "type": "number"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};

export const commsTemplatesModule: ModuleConfig = {
  key: "commsTemplates",
  title: "Message Templates",
  icon: "Mt",
  group: "Communication & Portal",
  feature: "parent_communication",
  endpoint: "/communications/templates",
  titleField: "template_name",
  subtitleField: "channel",
  searchFields: ["template_name", "channel", "category", "audience"],
  listColumns: [{"key": "category", "label": "Category"}, {"key": "audience", "label": "Audience"}, {"key": "subject", "label": "Subject"}, {"key": "body", "label": "Body"}],
  formFields: [{"key": "template_name", "label": "Template Name", "type": "text", "required": true}, {"key": "channel", "label": "Channel", "type": "select", "options": [{"label": "WhatsApp", "value": "WhatsApp"}, {"label": "SMS", "value": "SMS"}, {"label": "Email", "value": "Email"}, {"label": "In App", "value": "In App"}]}, {"key": "category", "label": "Category", "type": "text", "required": true}, {"key": "audience", "label": "Audience", "type": "select", "options": [{"label": "Parents", "value": "Parents"}, {"label": "Students", "value": "Students"}, {"label": "Staff", "value": "Staff"}, {"label": "All", "value": "All"}]}, {"key": "subject", "label": "Subject", "type": "lookup", "lookup": {"endpoint": "/subjects", "valueField": "subject_name", "searchFields": ["subject_name", "subject_code"], "subtitleFields": ["subject_code"]}}, {"key": "body", "label": "Body", "type": "textarea", "required": true}, {"key": "variables", "label": "Variables", "type": "text"}, {"key": "language", "label": "Language", "type": "select", "options": [{"label": "English", "value": "English"}, {"label": "Hindi", "value": "Hindi"}, {"label": "Bengali", "value": "Bengali"}, {"label": "Tamil", "value": "Tamil"}, {"label": "Telugu", "value": "Telugu"}, {"label": "Marathi", "value": "Marathi"}, {"label": "Gujarati", "value": "Gujarati"}]}, {"key": "status", "label": "Status", "type": "select", "options": [{"label": "Active", "value": "Active"}, {"label": "Inactive", "value": "Inactive"}, {"label": "Draft", "value": "Draft"}]}, {"key": "remarks", "label": "Remarks", "type": "textarea"}],
  allowCreate: true,
  allowEdit: true,
  allowDelete: true,
};
