export const MODULE_LAYOUT_LIMIT = 20;

export const MASTER_CATEGORIES = [
  "Class",
  "Exam",
  "Gender",
  "House",
  "Section",
  "BloodGroup",
  "Nationality",
  "TransportRoute",
  "StudentStatus",
  "Department",
  "Subject",
  "FeeType",
  "AttendanceStatus",
  "ExamType",
  "EmploymentType",
  "SalaryGrade",
  "AcademicYear",
];

export const MODULE_CONFIGS = {
  Students: {
    moduleName: "Students",
    title: "Student Layout Builder",
    subtitle: "Customize the Student module form layout.",
    backPath: "/students",
    storageKey: "student_form_layout_v1",
    defaultLayout: [
      {
        id: "academic_info",
        title: "Academic Information",
        fields: [
          {
            id: "field_admission_no",
            name: "admission_no",
            label: "Admission No",
            type: "singleline",
            required: true,
            source: "system",
            placeholder: "ADM001",
          },
          {
            id: "field_roll_no",
            name: "roll_no",
            label: "Roll No",
            type: "singleline",
            required: false,
            source: "system",
          },
          {
            id: "field_class_name",
            name: "class_name",
            label: "Class",
            type: "picklist",
            required: false,
            source: "system",
            masterCategory: "Class",
          },
          {
            id: "field_section",
            name: "section",
            label: "Section",
            type: "picklist",
            required: false,
            source: "system",
            masterCategory: "Section",
          },
          {
            id: "field_house",
            name: "house",
            label: "House",
            type: "picklist",
            required: false,
            source: "system",
            masterCategory: "House",
          },
          {
            id: "field_admission_date",
            name: "admission_date",
            label: "Admission Date",
            type: "date",
            required: false,
            source: "system",
          },
          {
            id: "field_student_status",
            name: "student_status",
            label: "Student Status",
            type: "picklist",
            required: false,
            source: "system",
            masterCategory: "StudentStatus",
          },
          {
            id: "field_residential_type",
            name: "residential_type",
            label: "Residential Type",
            type: "picklist",
            required: false,
            source: "system",
            masterCategory: "ResidentialType",
          },
        ],
      },
      {
        id: "personal_info",
        title: "Personal Information",
        fields: [
          {
            id: "field_first_name",
            name: "first_name",
            label: "First Name",
            type: "singleline",
            required: true,
            source: "system",
          },
          {
            id: "field_last_name",
            name: "last_name",
            label: "Last Name",
            type: "singleline",
            required: false,
            source: "system",
          },
          {
            id: "field_gender",
            name: "gender",
            label: "Gender",
            type: "picklist",
            required: false,
            source: "system",
            masterCategory: "Gender",
          },
          {
            id: "field_dob",
            name: "dob",
            label: "Date of Birth",
            type: "date",
            required: false,
            source: "system",
          },
          {
            id: "field_nationality",
            name: "nationality",
            label: "Nationality",
            type: "picklist",
            required: false,
            source: "system",
            masterCategory: "Nationality",
          },
          {
            id: "field_blood_group",
            name: "blood_group",
            label: "Blood Group",
            type: "picklist",
            required: false,
            source: "system",
            masterCategory: "BloodGroup",
          },
          {
            id: "field_photo_url",
            name: "photo_url",
            label: "Photo URL",
            type: "url",
            required: false,
            source: "system",
            placeholder: "https://...",
          },
        ],
      },
      {
        id: "guardian_info",
        title: "Parent / Guardian Information",
        fields: [
          {
            id: "field_father_name",
            name: "father_name",
            label: "Father Name",
            type: "singleline",
            required: false,
            source: "system",
          },
          {
            id: "field_mother_name",
            name: "mother_name",
            label: "Mother Name",
            type: "singleline",
            required: false,
            source: "system",
          },
          {
            id: "field_guardian_name",
            name: "guardian_name",
            label: "Guardian Name",
            type: "singleline",
            required: false,
            source: "system",
          },
          {
            id: "field_guardian_phone",
            name: "guardian_phone",
            label: "Guardian Phone",
            type: "phone",
            required: false,
            source: "system",
          },
          {
            id: "field_guardian_email",
            name: "guardian_email",
            label: "Guardian Email",
            type: "email",
            required: false,
            source: "system",
          },
        ],
      },
      {
        id: "health_transport",
        title: "Health & Transport",
        fields: [
          {
            id: "field_medical_notes",
            name: "medical_notes",
            label: "Medical Notes",
            type: "multiline",
            required: false,
            source: "system",
          },
          {
            id: "field_allergies",
            name: "allergies",
            label: "Allergies",
            type: "multiline",
            required: false,
            source: "system",
          },
          {
            id: "field_transport_route",
            name: "transport_route",
            label: "Transport Route",
            type: "picklist",
            required: false,
            source: "system",
            masterCategory: "TransportRoute",
          },
          {
            id: "field_pickup_point",
            name: "pickup_point",
            label: "Pickup Point",
            type: "singleline",
            required: false,
            source: "system",
          },
        ],
      },
      {
        id: "documents",
        title: "Documents",
        fields: [
          {
            id: "field_birth_certificate",
            name: "birth_certificate",
            label: "Birth Certificate",
            type: "singleline",
            required: false,
            source: "system",
          },
          {
            id: "field_transfer_certificate",
            name: "transfer_certificate",
            label: "Transfer Certificate",
            type: "singleline",
            required: false,
            source: "system",
          },
          {
            id: "field_passport_no",
            name: "passport_no",
            label: "Passport No",
            type: "singleline",
            required: false,
            source: "system",
          },
        ],
      },
    ],
  },

  Teachers: {
    moduleName: "Teachers",
    title: "Teacher Layout Builder",
    subtitle: "Customize the Teacher module form layout.",
    backPath: "/teachers",
    storageKey: "teacher_form_layout_v1",
    defaultLayout: [
      {
        id: "teacher_basic",
        title: "Basic Information",
        fields: [
          {
            id: "field_teacher_code",
            name: "teacher_code",
            label: "Teacher Code",
            type: "singleline",
            required: true,
            source: "system",
          },
          {
            id: "field_is_class_teacher",
            name: "is_class_teacher",
            label: "Is Class Teacher",
            type: "checkbox",
            required: false,
            source: "system",
          },
          {
            id: "field_class_id",
            name: "class_id",
            label: "Class",
            type: "lookup",
            required: false,
            source: "system",
          },
          {
            id: "field_first_name",
            name: "first_name",
            label: "First Name",
            type: "singleline",
            required: true,
            source: "system",
          },
          {
            id: "field_last_name",
            name: "last_name",
            label: "Last Name",
            type: "singleline",
            required: false,
            source: "system",
          },
          {
            id: "field_gender",
            name: "gender",
            label: "Gender",
            type: "picklist",
            required: false,
            source: "system",
            masterCategory: "Gender",
          },
          {
            id: "field_phone",
            name: "phone",
            label: "Phone",
            type: "phone",
            required: false,
            source: "system",
          },
          {
            id: "field_email",
            name: "email",
            label: "Email",
            type: "email",
            required: false,
            source: "system",
          },
        ],
      },
      {
        id: "teacher_work",
        title: "Employment Information",
        fields: [
          {
            id: "field_department",
            name: "department",
            label: "Department",
            type: "picklist",
            required: false,
            source: "system",
            masterCategory: "Department",
          },
          {
            id: "field_subject",
            name: "subject",
            label: "Subject",
            type: "picklist",
            required: false,
            source: "system",
            masterCategory: "Subject",
          },
          {
            id: "field_employment_type",
            name: "employment_type",
            label: "Employment Type",
            type: "picklist",
            required: false,
            source: "system",
            masterCategory: "EmploymentType",
          },
          {
            id: "field_joining_date",
            name: "joining_date",
            label: "Joining Date",
            type: "date",
            required: false,
            source: "system",
          },
        ],
      },
    ],
  },

  Classes: {
    moduleName: "Classes",
    title: "Class Layout Builder",
    subtitle: "Customize the Classes module form layout.",
    backPath: "/classes",
    storageKey: "class_form_layout_v1",
    defaultLayout: [
      {
        id: "class_basic",
        title: "Class Information",
        fields: [
          {
            id: "field_class_name",
            name: "class_name",
            label: "Class Name",
            type: "picklist",
            required: true,
            source: "system",
            masterCategory: "Class",
          },
          {
            id: "field_section",
            name: "section",
            label: "Section",
            type: "picklist",
            required: true,
            source: "system",
            masterCategory: "Section",
          },
          {
            id: "field_class_teacher_id",
            name: "class_teacher_id",
            label: "Class Teacher",
            type: "lookup",
            required: false,
            source: "system",
          },
          {
            id: "field_room_no",
            name: "room_no",
            label: "Room No",
            type: "singleline",
            required: false,
            source: "system",
          },
        ],
      },
    ],
  },

  Fees: {
    moduleName: "Fees",
    title: "Fees Layout Builder",
    subtitle: "Customize the Fees module form layout.",
    backPath: "/fees",
    storageKey: "fees_form_layout_v1",
    defaultLayout: [
      {
        id: "fees_basic",
        title: "Fee Information",
        fields: [
          {
            id: "field_student_id",
            name: "student_id",
            label: "Student",
            type: "number",
            required: true,
            source: "system",
          },
          {
            id: "field_fee_type",
            name: "fee_type",
            label: "Fee Type",
            type: "picklist",
            required: true,
            source: "system",
            masterCategory: "FeeType",
          },
          {
            id: "field_amount",
            name: "amount",
            label: "Amount",
            type: "decimal",
            required: true,
            source: "system",
          },
          {
            id: "field_due_date",
            name: "due_date",
            label: "Due Date",
            type: "date",
            required: false,
            source: "system",
          },
          {
            id: "field_status",
            name: "status",
            label: "Status",
            type: "picklist",
            required: false,
            source: "system",
          },
        ],
      },
    ],
  },

  Attendance: {
    moduleName: "Attendance",
    title: "Attendance Layout Builder",
    subtitle: "Customize the Attendance module form layout.",
    backPath: "/attendance",
    storageKey: "attendance_form_layout_v1",
    defaultLayout: [
      {
        id: "attendance_basic",
        title: "Attendance Information",
        fields: [
          {
            id: "field_student_id",
            name: "student_id",
            label: "Student",
            type: "number",
            required: true,
            source: "system",
          },
          {
            id: "field_attendance_date",
            name: "attendance_date",
            label: "Attendance Date",
            type: "date",
            required: true,
            source: "system",
          },
          {
            id: "field_status",
            name: "status",
            label: "Status",
            type: "picklist",
            required: true,
            source: "system",
            masterCategory: "AttendanceStatus",
          },
          {
            id: "field_remarks",
            name: "remarks",
            label: "Remarks",
            type: "multiline",
            required: false,
            source: "system",
          },
        ],
      },
    ],
  },

  Exams: {
  moduleName: "Exams",
  title: "Exam Layout Builder",
  subtitle: "Customize the Exams module form layout.",
  backPath: "/exams",
  storageKey: "exam_form_layout_v1",
  defaultLayout: [
    {
      id: "exam_information",
      title: "Exam Information",
      fields: [
        {
          id: "field_exam_name",
          name: "exam_name",
          label: "Exam Name",
          type: "singleline",
          required: true,
          source: "system",
        },
        {
          id: "field_exam_type",
          name: "exam_type",
          label: "Exam Type",
          type: "picklist",
          required: true,
          source: "system",
          masterCategory: "ExamType",
        },
        {
          id: "field_remarks",
          name: "remarks",
          label: "Remarks",
          type: "multiline",
          required: false,
          source: "system",
        },
      ],
    },
  ],
},
  Marks: {
    moduleName: "Marks",
    title: "Marks Layout Builder",
    subtitle: "Customize the Marks module form layout.",
    backPath: "/marks",
    storageKey: "marks_form_layout_v1",
    defaultLayout: [
      {
        id: "marks_basic",
        title: "Marks Information",
        fields: [
          {
            id: "field_student_id",
            name: "student_id",
            label: "Student",
            type: "number",
            required: true,
            source: "system",
          },
          {
            id: "field_exam_id",
            name: "exam_id",
            label: "Exam",
            type: "number",
            required: true,
            source: "system",
          },
          {
            id: "field_subject",
            name: "subject",
            label: "Subject",
            type: "picklist",
            required: true,
            source: "system",
            masterCategory: "Subject",
          },
          {
            id: "field_marks_obtained",
            name: "marks_obtained",
            label: "Marks Obtained",
            type: "decimal",
            required: true,
            source: "system",
          },
          {
            id: "field_max_marks",
            name: "max_marks",
            label: "Max Marks",
            type: "decimal",
            required: true,
            source: "system",
          },
        ],
      },
    ],
  },
};
