"""baseline tenant schema

Revision ID: bc8c44c89af8
Revises: 
Create Date: 2026-07-06 06:46:02.049604
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8c44c89af8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_years_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_years_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_years_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_academic_years_status'), ['status'], unique=False)

    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('class_teacher', sa.String(), nullable=True),
    sa.Column('room_number', sa.String(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=True),
    sa.Column('class_teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_class_teacher_id'), ['class_teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_id'), ['id'], unique=False)

    op.create_table('communication_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('audience', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communication_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communication_templates_audience'), ['audience'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_templates_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_templates_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_templates_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_templates_template_name'), ['template_name'], unique=True)

    op.create_table('compliance_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_code', sa.String(), nullable=False),
    sa.Column('accreditation_body', sa.String(), nullable=False),
    sa.Column('standard_area', sa.String(), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('evidence_link', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('finding', sa.Text(), nullable=True),
    sa.Column('action_plan', sa.Text(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_tasks_accreditation_body'), ['accreditation_body'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_tasks_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_tasks_review_date'), ['review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_tasks_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_tasks_standard_area'), ['standard_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_tasks_task_code'), ['task_code'], unique=True)

    op.create_table('enrichment_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_code', sa.String(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('coordinator', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('eligible_classes', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('enrolled_count', sa.Integer(), nullable=True),
    sa.Column('fee_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrichment_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrichment_activities_activity_code'), ['activity_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_enrichment_activities_activity_name'), ['activity_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_activities_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_activities_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_activities_coordinator'), ['coordinator'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_activities_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_activities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_activities_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_activities_status'), ['status'], unique=False)

    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_name', sa.String(), nullable=False),
    sa.Column('exam_type', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_id'), ['id'], unique=False)

    op.create_table('fee_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('residential_type', sa.String(), nullable=True),
    sa.Column('fee_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year', 'class_name', 'residential_type', 'fee_type', name='uq_fee_structure_year_class_res_type')
    )
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_structures_academic_year'), ['academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_structures_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_structures_fee_type'), ['fee_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_structures_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_structures_residential_type'), ['residential_type'], unique=False)

    op.create_table('hostel_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_name', sa.String(), nullable=False),
    sa.Column('hostel_type', sa.String(), nullable=False),
    sa.Column('warden_name', sa.String(), nullable=True),
    sa.Column('warden_phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hostel_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hostel_blocks_block_name'), ['block_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_hostel_blocks_id'), ['id'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_code', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('quantity_available', sa.Float(), nullable=True),
    sa.Column('reorder_level', sa.Float(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_item_code'), ['item_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_items_item_name'), ['item_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_status'), ['status'], unique=False)

    op.create_table('library_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accession_no', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('total_copies', sa.Integer(), nullable=True),
    sa.Column('available_copies', sa.Integer(), nullable=True),
    sa.Column('shelf_no', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_books_accession_no'), ['accession_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_library_books_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_books_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_books_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_books_title'), ['title'], unique=False)

    op.create_table('master_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_data_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_data_id'), ['id'], unique=False)

    op.create_table('mess_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('menu_items', sa.Text(), nullable=False),
    sa.Column('nutrition_notes', sa.String(), nullable=True),
    sa.Column('allergen_notes', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_date', 'meal_type', name='uq_mess_menu_date_meal')
    )
    with op.batch_alter_table('mess_menus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mess_menus_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mess_menus_meal_type'), ['meal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mess_menus_menu_date'), ['menu_date'], unique=False)

    op.create_table('module_custom_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('field_label', sa.String(), nullable=True),
    sa.Column('field_type', sa.String(), nullable=True),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_name', 'record_id', 'field_key', name='uq_module_record_custom_field_value')
    )
    with op.batch_alter_table('module_custom_field_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_custom_field_values_field_key'), ['field_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_custom_field_values_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_custom_field_values_module_name'), ['module_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_custom_field_values_record_id'), ['record_id'], unique=False)

    op.create_table('module_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('layout_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('module_layouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_layouts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_layouts_module_name'), ['module_name'], unique=True)

    op.create_table('school_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=False),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('institution_type', sa.String(), nullable=True),
    sa.Column('board_affiliation', sa.String(), nullable=True),
    sa.Column('school_code', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('campus_name', sa.String(), nullable=True),
    sa.Column('campus_city', sa.String(), nullable=True),
    sa.Column('campus_state', sa.String(), nullable=True),
    sa.Column('campus_country', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('principal_name', sa.String(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=True),
    sa.Column('default_sections', sa.String(), nullable=True),
    sa.Column('houses', sa.String(), nullable=True),
    sa.Column('working_days', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('receipt_prefix', sa.String(), nullable=True),
    sa.Column('late_fee_rule', sa.String(), nullable=True),
    sa.Column('pass_percentage', sa.Float(), nullable=True),
    sa.Column('grade_rules', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_settings_id'), ['id'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_subject_code'), ['subject_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_subjects_subject_name'), ['subject_name'], unique=False)

    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_no', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('assigned_class', sa.String(), nullable=True),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('salary_grade', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('is_class_teacher', sa.Boolean(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teachers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_teachers_employee_no'), ['employee_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_teachers_id'), ['id'], unique=False)

    op.create_table('transport_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(), nullable=False),
    sa.Column('start_point', sa.String(), nullable=True),
    sa.Column('end_point', sa.String(), nullable=True),
    sa.Column('monthly_fee', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_routes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_routes_route_name'), ['route_name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('class_exam_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'exam_id', 'academic_year', name='uq_class_exam_academic_year')
    )
    with op.batch_alter_table('class_exam_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_exam_mappings_academic_year'), ['academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_exam_mappings_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_exam_mappings_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_exam_mappings_id'), ['id'], unique=False)

    op.create_table('class_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('weekly_periods', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'academic_year', 'subject_name', name='uq_class_subject_name')
    )
    with op.batch_alter_table('class_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_subjects_academic_year'), ['academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_subjects_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_subjects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_subjects_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_subjects_subject_name'), ['subject_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_subjects_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('communication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=False),
    sa.Column('recipient_phone', sa.String(), nullable=True),
    sa.Column('recipient_email', sa.String(), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('related_module', sa.String(), nullable=True),
    sa.Column('related_record_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['communication_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communication_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communication_logs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_logs_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_logs_recipient_name'), ['recipient_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_logs_recipient_phone'), ['recipient_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_logs_related_module'), ['related_module'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_logs_template_id'), ['template_id'], unique=False)

    op.create_table('exam_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('component_name', sa.String(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=True),
    sa.Column('weightage', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_components_component_name'), ['component_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_components_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_components_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_components_is_active'), ['is_active'], unique=False)

    op.create_table('hostel_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('room_no', sa.String(), nullable=False),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['hostel_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'room_no', name='uq_hostel_block_room')
    )
    with op.batch_alter_table('hostel_rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hostel_rooms_block_id'), ['block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hostel_rooms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hostel_rooms_room_no'), ['room_no'], unique=False)

    op.create_table('multi_curriculum_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('curriculum_track', sa.String(), nullable=False),
    sa.Column('grade_level', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('subject_groups', sa.Text(), nullable=True),
    sa.Column('assessment_model', sa.String(), nullable=True),
    sa.Column('coordinator', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('multi_curriculum_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_multi_curriculum_plans_academic_year'), ['academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_multi_curriculum_plans_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_multi_curriculum_plans_curriculum_track'), ['curriculum_track'], unique=False)
        batch_op.create_index(batch_op.f('ix_multi_curriculum_plans_grade_level'), ['grade_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_multi_curriculum_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_multi_curriculum_plans_program_name'), ['program_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_multi_curriculum_plans_status'), ['status'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_no', sa.String(), nullable=False),
    sa.Column('roll_no', sa.String(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('house', sa.String(), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('student_status', sa.String(), nullable=True),
    sa.Column('residential_type', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('blood_group', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('mother_name', sa.String(), nullable=True),
    sa.Column('guardian_name', sa.String(), nullable=True),
    sa.Column('guardian_phone', sa.String(), nullable=True),
    sa.Column('guardian_email', sa.String(), nullable=True),
    sa.Column('medical_notes', sa.String(), nullable=True),
    sa.Column('allergies', sa.String(), nullable=True),
    sa.Column('transport_route', sa.String(), nullable=True),
    sa.Column('pickup_point', sa.String(), nullable=True),
    sa.Column('birth_certificate', sa.String(), nullable=True),
    sa.Column('transfer_certificate', sa.String(), nullable=True),
    sa.Column('passport_no', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_admission_no'), ['admission_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_id'), ['id'], unique=False)

    op.create_table('transport_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stop_name', sa.String(), nullable=False),
    sa.Column('pickup_time', sa.String(), nullable=True),
    sa.Column('drop_time', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['transport_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'stop_name', name='uq_transport_route_stop')
    )
    with op.batch_alter_table('transport_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_stops_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_stops_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_stops_stop_name'), ['stop_name'], unique=False)

    op.create_table('transport_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_no', sa.String(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('driver_phone', sa.String(), nullable=True),
    sa.Column('attendant_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['transport_routes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_vehicles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_vehicles_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_vehicles_vehicle_no'), ['vehicle_no'], unique=True)

    op.create_table('admission_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_no', sa.String(), nullable=False),
    sa.Column('student_name', sa.String(), nullable=False),
    sa.Column('grade_applying', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('guardian_name', sa.String(), nullable=False),
    sa.Column('guardian_phone', sa.String(), nullable=False),
    sa.Column('guardian_email', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('converted_student_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['converted_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admission_inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admission_inquiries_academic_year'), ['academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_inquiries_converted_student_id'), ['converted_student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_inquiries_follow_up_date'), ['follow_up_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_inquiries_grade_applying'), ['grade_applying'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_inquiries_guardian_phone'), ['guardian_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_inquiries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_inquiries_inquiry_no'), ['inquiry_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_admission_inquiries_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_inquiries_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_inquiries_student_name'), ['student_name'], unique=False)

    op.create_table('alumni_withdrawal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_no', sa.String(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(), nullable=False),
    sa.Column('admission_no', sa.String(), nullable=True),
    sa.Column('last_class', sa.String(), nullable=True),
    sa.Column('record_type', sa.String(), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('leaving_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('destination_school', sa.String(), nullable=True),
    sa.Column('destination_country', sa.String(), nullable=True),
    sa.Column('certificate_status', sa.String(), nullable=True),
    sa.Column('alumni_email', sa.String(), nullable=True),
    sa.Column('alumni_phone', sa.String(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alumni_withdrawal_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alumni_withdrawal_records_admission_no'), ['admission_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_alumni_withdrawal_records_alumni_phone'), ['alumni_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_alumni_withdrawal_records_certificate_status'), ['certificate_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alumni_withdrawal_records_current_status'), ['current_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alumni_withdrawal_records_destination_country'), ['destination_country'], unique=False)
        batch_op.create_index(batch_op.f('ix_alumni_withdrawal_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alumni_withdrawal_records_last_class'), ['last_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_alumni_withdrawal_records_leaving_date'), ['leaving_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_alumni_withdrawal_records_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_alumni_withdrawal_records_record_no'), ['record_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_alumni_withdrawal_records_record_type'), ['record_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alumni_withdrawal_records_request_date'), ['request_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_alumni_withdrawal_records_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alumni_withdrawal_records_student_name'), ['student_name'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('class_name_snapshot', sa.String(), nullable=True),
    sa.Column('section_snapshot', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_academic_year'), ['academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_id'), ['id'], unique=False)

    op.create_table('counseling_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_no', sa.String(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('concern_type', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('reported_by', sa.String(), nullable=True),
    sa.Column('counselor', sa.String(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.Column('guardian_contacted', sa.Boolean(), nullable=True),
    sa.Column('action_plan', sa.Text(), nullable=True),
    sa.Column('confidentiality_level', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counseling_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counseling_cases_case_no'), ['case_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_counseling_cases_concern_type'), ['concern_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_counseling_cases_confidentiality_level'), ['confidentiality_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_counseling_cases_counselor'), ['counselor'], unique=False)
        batch_op.create_index(batch_op.f('ix_counseling_cases_guardian_contacted'), ['guardian_contacted'], unique=False)
        batch_op.create_index(batch_op.f('ix_counseling_cases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_counseling_cases_next_follow_up_date'), ['next_follow_up_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_counseling_cases_reported_by'), ['reported_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_counseling_cases_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_counseling_cases_session_date'), ['session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_counseling_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_counseling_cases_student_id'), ['student_id'], unique=False)

    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fee_type', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('class_name_snapshot', sa.String(), nullable=True),
    sa.Column('section_snapshot', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('due_amount', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('receipt_no', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fees_academic_year'), ['academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_fees_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fees_id'), ['id'], unique=False)

    op.create_table('health_infirmary_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('visit_time', sa.String(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('medicine_given', sa.String(), nullable=True),
    sa.Column('attended_by', sa.String(), nullable=True),
    sa.Column('referred_to_hospital', sa.Boolean(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_infirmary_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_infirmary_visits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_infirmary_visits_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_infirmary_visits_student_id'), ['student_id'], unique=False)

    op.create_table('hostel_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('bed_no', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['hostel_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'bed_no', 'status', name='uq_active_hostel_bed')
    )
    with op.batch_alter_table('hostel_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hostel_allocations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hostel_allocations_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hostel_allocations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_hostel_allocations_student_id'), ['student_id'], unique=False)

    op.create_table('international_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('document_no', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('issuing_country', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('verified_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('international_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_international_documents_document_no'), ['document_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_international_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_international_documents_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_international_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_international_documents_issuing_country'), ['issuing_country'], unique=False)
        batch_op.create_index(batch_op.f('ix_international_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_international_documents_student_id'), ['student_id'], unique=False)

    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('issued_to_student_id', sa.Integer(), nullable=True),
    sa.Column('issued_to_staff', sa.String(), nullable=True),
    sa.Column('reference_no', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issued_to_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_issued_to_student_id'), ['issued_to_student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_transaction_type'), ['transaction_type'], unique=False)

    op.create_table('library_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fine_amount', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['library_books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_issues_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_issues_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_issues_issue_date'), ['issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_issues_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_issues_student_id'), ['student_id'], unique=False)

    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('class_subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('class_name_snapshot', sa.String(), nullable=True),
    sa.Column('section_snapshot', sa.String(), nullable=True),
    sa.Column('exam_name_snapshot', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_subject_id'], ['class_subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marks_academic_year'), ['academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_marks_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marks_class_subject_id'), ['class_subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marks_subject_name'), ['subject_name'], unique=False)

    op.create_table('mess_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'meal_date', 'meal_type', name='uq_mess_student_meal_attendance')
    )
    with op.batch_alter_table('mess_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mess_attendance_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mess_attendance_meal_date'), ['meal_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_mess_attendance_meal_type'), ['meal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mess_attendance_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mess_attendance_student_id'), ['student_id'], unique=False)

    op.create_table('parent_student_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'student_id', name='uq_portal_link_user_student')
    )
    with op.batch_alter_table('parent_student_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_student_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_student_links_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_student_links_user_id'), ['user_id'], unique=False)

    op.create_table('student_custom_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('field_label', sa.String(), nullable=True),
    sa.Column('field_type', sa.String(), nullable=True),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'field_key', name='uq_student_custom_field_value')
    )
    with op.batch_alter_table('student_custom_field_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_custom_field_values_field_key'), ['field_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_custom_field_values_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_custom_field_values_student_id'), ['student_id'], unique=False)

    op.create_table('student_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('class_name_snapshot', sa.String(), nullable=True),
    sa.Column('section_snapshot', sa.String(), nullable=True),
    sa.Column('roll_no', sa.String(), nullable=True),
    sa.Column('enrollment_status', sa.String(), nullable=True),
    sa.Column('promotion_status', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_id', 'academic_year', name='uq_student_enrollment_class_year')
    )
    with op.batch_alter_table('student_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_enrollments_academic_year'), ['academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_enrollments_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_enrollments_enrollment_status'), ['enrollment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_enrollments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_enrollments_promotion_status'), ['promotion_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_enrollments_student_id'), ['student_id'], unique=False)

    op.create_table('student_service_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_no', sa.String(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('requester_name', sa.String(), nullable=False),
    sa.Column('requester_role', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_service_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_service_tickets_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_service_tickets_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_service_tickets_contact_phone'), ['contact_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_service_tickets_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_service_tickets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_service_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_service_tickets_requester_name'), ['requester_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_service_tickets_requester_role'), ['requester_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_service_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_service_tickets_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_service_tickets_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_service_tickets_ticket_no'), ['ticket_no'], unique=True)

    op.create_table('transport_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['transport_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['transport_stops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['transport_vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_assignments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_assignments_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_assignments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_assignments_stop_id'), ['stop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_assignments_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_assignments_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('admission_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('panel_members', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['admission_inquiries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admission_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admission_assessments_assessment_type'), ['assessment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_assessments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_assessments_inquiry_id'), ['inquiry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_assessments_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_assessments_next_follow_up_date'), ['next_follow_up_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_assessments_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_assessments_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_assessments_status'), ['status'], unique=False)

    op.create_table('admission_follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('next_action', sa.String(), nullable=True),
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['admission_inquiries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admission_follow_ups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admission_follow_ups_activity_date'), ['activity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_follow_ups_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_follow_ups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_follow_ups_inquiry_id'), ['inquiry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_follow_ups_next_follow_up_date'), ['next_follow_up_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_follow_ups_outcome'), ['outcome'], unique=False)

    op.create_table('mark_component_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mark_id', sa.Integer(), nullable=False),
    sa.Column('exam_component_id', sa.Integer(), nullable=True),
    sa.Column('component_name', sa.String(), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=True),
    sa.Column('max_marks', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exam_component_id'], ['exam_components.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mark_id'], ['marks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mark_component_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mark_component_scores_exam_component_id'), ['exam_component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mark_component_scores_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mark_component_scores_mark_id'), ['mark_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mark_component_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mark_component_scores_mark_id'))
        batch_op.drop_index(batch_op.f('ix_mark_component_scores_id'))
        batch_op.drop_index(batch_op.f('ix_mark_component_scores_exam_component_id'))

    op.drop_table('mark_component_scores')
    with op.batch_alter_table('admission_follow_ups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admission_follow_ups_outcome'))
        batch_op.drop_index(batch_op.f('ix_admission_follow_ups_next_follow_up_date'))
        batch_op.drop_index(batch_op.f('ix_admission_follow_ups_inquiry_id'))
        batch_op.drop_index(batch_op.f('ix_admission_follow_ups_id'))
        batch_op.drop_index(batch_op.f('ix_admission_follow_ups_activity_type'))
        batch_op.drop_index(batch_op.f('ix_admission_follow_ups_activity_date'))

    op.drop_table('admission_follow_ups')
    with op.batch_alter_table('admission_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admission_assessments_status'))
        batch_op.drop_index(batch_op.f('ix_admission_assessments_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_admission_assessments_outcome'))
        batch_op.drop_index(batch_op.f('ix_admission_assessments_next_follow_up_date'))
        batch_op.drop_index(batch_op.f('ix_admission_assessments_mode'))
        batch_op.drop_index(batch_op.f('ix_admission_assessments_inquiry_id'))
        batch_op.drop_index(batch_op.f('ix_admission_assessments_id'))
        batch_op.drop_index(batch_op.f('ix_admission_assessments_assessment_type'))

    op.drop_table('admission_assessments')
    with op.batch_alter_table('transport_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_assignments_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_transport_assignments_student_id'))
        batch_op.drop_index(batch_op.f('ix_transport_assignments_stop_id'))
        batch_op.drop_index(batch_op.f('ix_transport_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_transport_assignments_route_id'))
        batch_op.drop_index(batch_op.f('ix_transport_assignments_id'))

    op.drop_table('transport_assignments')
    with op.batch_alter_table('student_service_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_service_tickets_ticket_no'))
        batch_op.drop_index(batch_op.f('ix_student_service_tickets_subject'))
        batch_op.drop_index(batch_op.f('ix_student_service_tickets_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_service_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_student_service_tickets_requester_role'))
        batch_op.drop_index(batch_op.f('ix_student_service_tickets_requester_name'))
        batch_op.drop_index(batch_op.f('ix_student_service_tickets_priority'))
        batch_op.drop_index(batch_op.f('ix_student_service_tickets_id'))
        batch_op.drop_index(batch_op.f('ix_student_service_tickets_due_date'))
        batch_op.drop_index(batch_op.f('ix_student_service_tickets_contact_phone'))
        batch_op.drop_index(batch_op.f('ix_student_service_tickets_category'))
        batch_op.drop_index(batch_op.f('ix_student_service_tickets_assigned_to'))

    op.drop_table('student_service_tickets')
    with op.batch_alter_table('student_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_enrollments_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_enrollments_promotion_status'))
        batch_op.drop_index(batch_op.f('ix_student_enrollments_id'))
        batch_op.drop_index(batch_op.f('ix_student_enrollments_enrollment_status'))
        batch_op.drop_index(batch_op.f('ix_student_enrollments_class_id'))
        batch_op.drop_index(batch_op.f('ix_student_enrollments_academic_year'))

    op.drop_table('student_enrollments')
    with op.batch_alter_table('student_custom_field_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_custom_field_values_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_custom_field_values_id'))
        batch_op.drop_index(batch_op.f('ix_student_custom_field_values_field_key'))

    op.drop_table('student_custom_field_values')
    with op.batch_alter_table('parent_student_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_student_links_user_id'))
        batch_op.drop_index(batch_op.f('ix_parent_student_links_student_id'))
        batch_op.drop_index(batch_op.f('ix_parent_student_links_id'))

    op.drop_table('parent_student_links')
    with op.batch_alter_table('mess_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mess_attendance_student_id'))
        batch_op.drop_index(batch_op.f('ix_mess_attendance_status'))
        batch_op.drop_index(batch_op.f('ix_mess_attendance_meal_type'))
        batch_op.drop_index(batch_op.f('ix_mess_attendance_meal_date'))
        batch_op.drop_index(batch_op.f('ix_mess_attendance_id'))

    op.drop_table('mess_attendance')
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marks_subject_name'))
        batch_op.drop_index(batch_op.f('ix_marks_id'))
        batch_op.drop_index(batch_op.f('ix_marks_class_subject_id'))
        batch_op.drop_index(batch_op.f('ix_marks_class_id'))
        batch_op.drop_index(batch_op.f('ix_marks_academic_year'))

    op.drop_table('marks')
    with op.batch_alter_table('library_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_issues_student_id'))
        batch_op.drop_index(batch_op.f('ix_library_issues_status'))
        batch_op.drop_index(batch_op.f('ix_library_issues_issue_date'))
        batch_op.drop_index(batch_op.f('ix_library_issues_id'))
        batch_op.drop_index(batch_op.f('ix_library_issues_book_id'))

    op.drop_table('library_issues')
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_issued_to_student_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_id'))

    op.drop_table('inventory_transactions')
    with op.batch_alter_table('international_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_international_documents_student_id'))
        batch_op.drop_index(batch_op.f('ix_international_documents_status'))
        batch_op.drop_index(batch_op.f('ix_international_documents_issuing_country'))
        batch_op.drop_index(batch_op.f('ix_international_documents_id'))
        batch_op.drop_index(batch_op.f('ix_international_documents_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_international_documents_document_type'))
        batch_op.drop_index(batch_op.f('ix_international_documents_document_no'))

    op.drop_table('international_documents')
    with op.batch_alter_table('hostel_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hostel_allocations_student_id'))
        batch_op.drop_index(batch_op.f('ix_hostel_allocations_status'))
        batch_op.drop_index(batch_op.f('ix_hostel_allocations_room_id'))
        batch_op.drop_index(batch_op.f('ix_hostel_allocations_id'))

    op.drop_table('hostel_allocations')
    with op.batch_alter_table('health_infirmary_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_infirmary_visits_student_id'))
        batch_op.drop_index(batch_op.f('ix_health_infirmary_visits_status'))
        batch_op.drop_index(batch_op.f('ix_health_infirmary_visits_id'))

    op.drop_table('health_infirmary_visits')
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fees_id'))
        batch_op.drop_index(batch_op.f('ix_fees_class_id'))
        batch_op.drop_index(batch_op.f('ix_fees_academic_year'))

    op.drop_table('fees')
    with op.batch_alter_table('counseling_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counseling_cases_student_id'))
        batch_op.drop_index(batch_op.f('ix_counseling_cases_status'))
        batch_op.drop_index(batch_op.f('ix_counseling_cases_session_date'))
        batch_op.drop_index(batch_op.f('ix_counseling_cases_risk_level'))
        batch_op.drop_index(batch_op.f('ix_counseling_cases_reported_by'))
        batch_op.drop_index(batch_op.f('ix_counseling_cases_next_follow_up_date'))
        batch_op.drop_index(batch_op.f('ix_counseling_cases_id'))
        batch_op.drop_index(batch_op.f('ix_counseling_cases_guardian_contacted'))
        batch_op.drop_index(batch_op.f('ix_counseling_cases_counselor'))
        batch_op.drop_index(batch_op.f('ix_counseling_cases_confidentiality_level'))
        batch_op.drop_index(batch_op.f('ix_counseling_cases_concern_type'))
        batch_op.drop_index(batch_op.f('ix_counseling_cases_case_no'))

    op.drop_table('counseling_cases')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_class_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_academic_year'))

    op.drop_table('attendance')
    with op.batch_alter_table('alumni_withdrawal_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alumni_withdrawal_records_student_name'))
        batch_op.drop_index(batch_op.f('ix_alumni_withdrawal_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_alumni_withdrawal_records_request_date'))
        batch_op.drop_index(batch_op.f('ix_alumni_withdrawal_records_record_type'))
        batch_op.drop_index(batch_op.f('ix_alumni_withdrawal_records_record_no'))
        batch_op.drop_index(batch_op.f('ix_alumni_withdrawal_records_reason'))
        batch_op.drop_index(batch_op.f('ix_alumni_withdrawal_records_leaving_date'))
        batch_op.drop_index(batch_op.f('ix_alumni_withdrawal_records_last_class'))
        batch_op.drop_index(batch_op.f('ix_alumni_withdrawal_records_id'))
        batch_op.drop_index(batch_op.f('ix_alumni_withdrawal_records_destination_country'))
        batch_op.drop_index(batch_op.f('ix_alumni_withdrawal_records_current_status'))
        batch_op.drop_index(batch_op.f('ix_alumni_withdrawal_records_certificate_status'))
        batch_op.drop_index(batch_op.f('ix_alumni_withdrawal_records_alumni_phone'))
        batch_op.drop_index(batch_op.f('ix_alumni_withdrawal_records_admission_no'))

    op.drop_table('alumni_withdrawal_records')
    with op.batch_alter_table('admission_inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admission_inquiries_student_name'))
        batch_op.drop_index(batch_op.f('ix_admission_inquiries_stage'))
        batch_op.drop_index(batch_op.f('ix_admission_inquiries_source'))
        batch_op.drop_index(batch_op.f('ix_admission_inquiries_inquiry_no'))
        batch_op.drop_index(batch_op.f('ix_admission_inquiries_id'))
        batch_op.drop_index(batch_op.f('ix_admission_inquiries_guardian_phone'))
        batch_op.drop_index(batch_op.f('ix_admission_inquiries_grade_applying'))
        batch_op.drop_index(batch_op.f('ix_admission_inquiries_follow_up_date'))
        batch_op.drop_index(batch_op.f('ix_admission_inquiries_converted_student_id'))
        batch_op.drop_index(batch_op.f('ix_admission_inquiries_academic_year'))

    op.drop_table('admission_inquiries')
    with op.batch_alter_table('transport_vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_vehicles_vehicle_no'))
        batch_op.drop_index(batch_op.f('ix_transport_vehicles_route_id'))
        batch_op.drop_index(batch_op.f('ix_transport_vehicles_id'))

    op.drop_table('transport_vehicles')
    with op.batch_alter_table('transport_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_stops_stop_name'))
        batch_op.drop_index(batch_op.f('ix_transport_stops_route_id'))
        batch_op.drop_index(batch_op.f('ix_transport_stops_id'))

    op.drop_table('transport_stops')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_id'))
        batch_op.drop_index(batch_op.f('ix_students_class_id'))
        batch_op.drop_index(batch_op.f('ix_students_admission_no'))

    op.drop_table('students')
    with op.batch_alter_table('multi_curriculum_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_multi_curriculum_plans_status'))
        batch_op.drop_index(batch_op.f('ix_multi_curriculum_plans_program_name'))
        batch_op.drop_index(batch_op.f('ix_multi_curriculum_plans_id'))
        batch_op.drop_index(batch_op.f('ix_multi_curriculum_plans_grade_level'))
        batch_op.drop_index(batch_op.f('ix_multi_curriculum_plans_curriculum_track'))
        batch_op.drop_index(batch_op.f('ix_multi_curriculum_plans_class_id'))
        batch_op.drop_index(batch_op.f('ix_multi_curriculum_plans_academic_year'))

    op.drop_table('multi_curriculum_plans')
    with op.batch_alter_table('hostel_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hostel_rooms_room_no'))
        batch_op.drop_index(batch_op.f('ix_hostel_rooms_id'))
        batch_op.drop_index(batch_op.f('ix_hostel_rooms_block_id'))

    op.drop_table('hostel_rooms')
    with op.batch_alter_table('exam_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_components_is_active'))
        batch_op.drop_index(batch_op.f('ix_exam_components_id'))
        batch_op.drop_index(batch_op.f('ix_exam_components_exam_id'))
        batch_op.drop_index(batch_op.f('ix_exam_components_component_name'))

    op.drop_table('exam_components')
    with op.batch_alter_table('communication_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communication_logs_template_id'))
        batch_op.drop_index(batch_op.f('ix_communication_logs_status'))
        batch_op.drop_index(batch_op.f('ix_communication_logs_related_module'))
        batch_op.drop_index(batch_op.f('ix_communication_logs_recipient_phone'))
        batch_op.drop_index(batch_op.f('ix_communication_logs_recipient_name'))
        batch_op.drop_index(batch_op.f('ix_communication_logs_id'))
        batch_op.drop_index(batch_op.f('ix_communication_logs_channel'))
        batch_op.drop_index(batch_op.f('ix_communication_logs_category'))

    op.drop_table('communication_logs')
    with op.batch_alter_table('class_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_subjects_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_class_subjects_subject_name'))
        batch_op.drop_index(batch_op.f('ix_class_subjects_subject_id'))
        batch_op.drop_index(batch_op.f('ix_class_subjects_id'))
        batch_op.drop_index(batch_op.f('ix_class_subjects_class_id'))
        batch_op.drop_index(batch_op.f('ix_class_subjects_academic_year'))

    op.drop_table('class_subjects')
    with op.batch_alter_table('class_exam_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_exam_mappings_id'))
        batch_op.drop_index(batch_op.f('ix_class_exam_mappings_exam_id'))
        batch_op.drop_index(batch_op.f('ix_class_exam_mappings_class_id'))
        batch_op.drop_index(batch_op.f('ix_class_exam_mappings_academic_year'))

    op.drop_table('class_exam_mappings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('transport_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_routes_route_name'))
        batch_op.drop_index(batch_op.f('ix_transport_routes_id'))

    op.drop_table('transport_routes')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_id'))
        batch_op.drop_index(batch_op.f('ix_teachers_employee_no'))
        batch_op.drop_index(batch_op.f('ix_teachers_email'))
        batch_op.drop_index(batch_op.f('ix_teachers_class_id'))

    op.drop_table('teachers')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_subject_name'))
        batch_op.drop_index(batch_op.f('ix_subjects_subject_code'))
        batch_op.drop_index(batch_op.f('ix_subjects_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('school_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_settings_id'))

    op.drop_table('school_settings')
    with op.batch_alter_table('module_layouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_layouts_module_name'))
        batch_op.drop_index(batch_op.f('ix_module_layouts_id'))

    op.drop_table('module_layouts')
    with op.batch_alter_table('module_custom_field_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_custom_field_values_record_id'))
        batch_op.drop_index(batch_op.f('ix_module_custom_field_values_module_name'))
        batch_op.drop_index(batch_op.f('ix_module_custom_field_values_id'))
        batch_op.drop_index(batch_op.f('ix_module_custom_field_values_field_key'))

    op.drop_table('module_custom_field_values')
    with op.batch_alter_table('mess_menus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mess_menus_menu_date'))
        batch_op.drop_index(batch_op.f('ix_mess_menus_meal_type'))
        batch_op.drop_index(batch_op.f('ix_mess_menus_id'))

    op.drop_table('mess_menus')
    with op.batch_alter_table('master_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_data_id'))
        batch_op.drop_index(batch_op.f('ix_master_data_category'))

    op.drop_table('master_data')
    with op.batch_alter_table('library_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_books_title'))
        batch_op.drop_index(batch_op.f('ix_library_books_status'))
        batch_op.drop_index(batch_op.f('ix_library_books_id'))
        batch_op.drop_index(batch_op.f('ix_library_books_category'))
        batch_op.drop_index(batch_op.f('ix_library_books_accession_no'))

    op.drop_table('library_books')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_status'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_item_name'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_item_code'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_category'))

    op.drop_table('inventory_items')
    with op.batch_alter_table('hostel_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hostel_blocks_id'))
        batch_op.drop_index(batch_op.f('ix_hostel_blocks_block_name'))

    op.drop_table('hostel_blocks')
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_structures_residential_type'))
        batch_op.drop_index(batch_op.f('ix_fee_structures_id'))
        batch_op.drop_index(batch_op.f('ix_fee_structures_fee_type'))
        batch_op.drop_index(batch_op.f('ix_fee_structures_class_name'))
        batch_op.drop_index(batch_op.f('ix_fee_structures_academic_year'))

    op.drop_table('fee_structures')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_id'))

    op.drop_table('exams')
    with op.batch_alter_table('enrichment_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrichment_activities_status'))
        batch_op.drop_index(batch_op.f('ix_enrichment_activities_start_date'))
        batch_op.drop_index(batch_op.f('ix_enrichment_activities_id'))
        batch_op.drop_index(batch_op.f('ix_enrichment_activities_end_date'))
        batch_op.drop_index(batch_op.f('ix_enrichment_activities_coordinator'))
        batch_op.drop_index(batch_op.f('ix_enrichment_activities_category'))
        batch_op.drop_index(batch_op.f('ix_enrichment_activities_activity_type'))
        batch_op.drop_index(batch_op.f('ix_enrichment_activities_activity_name'))
        batch_op.drop_index(batch_op.f('ix_enrichment_activities_activity_code'))

    op.drop_table('enrichment_activities')
    with op.batch_alter_table('compliance_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_tasks_task_code'))
        batch_op.drop_index(batch_op.f('ix_compliance_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_compliance_tasks_standard_area'))
        batch_op.drop_index(batch_op.f('ix_compliance_tasks_risk_level'))
        batch_op.drop_index(batch_op.f('ix_compliance_tasks_review_date'))
        batch_op.drop_index(batch_op.f('ix_compliance_tasks_owner'))
        batch_op.drop_index(batch_op.f('ix_compliance_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_compliance_tasks_accreditation_body'))

    op.drop_table('compliance_tasks')
    with op.batch_alter_table('communication_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communication_templates_template_name'))
        batch_op.drop_index(batch_op.f('ix_communication_templates_status'))
        batch_op.drop_index(batch_op.f('ix_communication_templates_language'))
        batch_op.drop_index(batch_op.f('ix_communication_templates_id'))
        batch_op.drop_index(batch_op.f('ix_communication_templates_channel'))
        batch_op.drop_index(batch_op.f('ix_communication_templates_category'))
        batch_op.drop_index(batch_op.f('ix_communication_templates_audience'))

    op.drop_table('communication_templates')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_id'))
        batch_op.drop_index(batch_op.f('ix_classes_class_teacher_id'))

    op.drop_table('classes')
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_years_status'))
        batch_op.drop_index(batch_op.f('ix_academic_years_name'))
        batch_op.drop_index(batch_op.f('ix_academic_years_is_current'))
        batch_op.drop_index(batch_op.f('ix_academic_years_id'))

    op.drop_table('academic_years')
    # ### end Alembic commands ###
